### PR TITLE
Implement PFHub wiki using Prose.io

### PR DESCRIPTION
**Pull request by wd15**
To review, please go to the wiki page at 

http://random-cat-797.surge.sh/wiki/

and try and edit the wiki page.

Instructions for editing are on the wiki page.

The preview on prose is messed up as it isn't getting all the CSS until this pull request is actually merged. 

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-797.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/797)

### CODE REVIEW

**Comment by tkphd** [comment]
Change request submitted, after allowing prose.io access to my GitHub profile.

**Comment by tkphd** [comment]
Looks like it created a branch on my own fork of PFHub, which I can then submit as a PR against the usnistgov repo. Is this the canonical workflow for prose.io wikis?

**Comment by wd15** [comment]
@tkphd, yup it forks for you basically. The point about using Prose.io over just using github is that you get to preview before submitting.

**Comment by wd15** [comment]
@tkphd, I'm working on making it look more like a wiki -- http://random-cat-797.surge.sh/wiki/.

I'll include some instructions about what prose.io is doing in the background. I'm going to move editable content under the wiki page such as the list of workshops and any other stuff like educational materials.

**Comment by tkphd** [comment]
Gotcha. OK!

**Comment by stvdwtt** [comment]
It seems like Prose.io needs read/write access to all of my public and private repos in order to link it up with GitHub. That seems excessive. I'm sure that there are technical reasons why they don't just want access limited to projects with Prose.io wikis, but it's unsettling.

**Comment by wd15** [comment]
@stvdwtt, agree on the concern, but people can make up their own minds, there are a issues on this, https://github.com/prose/prose/issues/897

**Comment by wd15** [comment]
@tkphd, can you check that you're happy with the latest version of this.

@stvdwtt, I think we're going to keep the wiki pages panel since Trevor seems to like it. Can you check this latest version and make sure you're basically happy with it.

**Comment by tkphd** [comment]
I'm not a fan of the "Pages" title, since it does not clearly convey that we're talking Wiki pages, rather than pages of the PFHub site writ large. I would prefer the format suggested in #810, *viz.*
> \<h5> Wiki \</h5>
> \[Main Page](wiki/main-page)
> \[Workshops](wiki/workshops)

**Comment by tkphd** [comment]
Also, to clarify: I also find Prose.io's draconian permissions unsettling. However, having a Wiki that can be edited as markdown is pretty cool, and no better tools seem to support doing so.

**Comment by wd15** [comment]
@tkphd, the title is now "Wiki Pages" is that ok?

**Comment by stvdwtt** [comment]
@tkphd Yeah, I get that there's a balance between security/privacy and functionality, and if this is the best (or only) tool to get us where we need to go, that it's worth it.

After a little bit of digging I figured out two things that make me feel better about the permissions settings. First, at the authorization screen there's the ability to only allow Prose to access public repos (instead of public and private). Also, on the organization level, there's an option to restrict access by third party apps unless they're on a white list. I'm a little surprised that that's not the default. Now that I know that I don't have to give access to every private repo in the PRISMS Center org, I'm feeling a lot better about it.

As far as the wiki panel goes, I think @tkphd's suggestions are good. Making it clear that the panel is only for navigating the wiki helps to clear things up and the gray box separates it nicely. Per @tkphd's comment, I think "Main Page" is clearer than "PFHub Wiki".

**Comment by wd15** [comment]
@tkphd, sorry  I forgot to change "PFHub Wiki" to "Main Page"

**Comment by wd15** [comment]
@stvdwtt, those changes must be fairly recent because people have been complaining about exactly the issues you raised. That's great news though.

**Pull request merged**
