### PR TITLE
Voorhees phase field lectures

### PR DESCRIPTION
**Pull request by wd15**
Address #795

Add Peter Voorhees youtube lectures on the wiki

The lectures: http://random-cat-810.surge.sh/wiki/voorhees-lectures/

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-810.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/810)

### CODE REVIEW

**Comment by stvdwtt** [comment]
I took a look and the lectures page looks good. The videos load and appear to be the correct ones.

I can move this to an issue or another PR, but I have to say that I'm not a big fan of the "Pages" sidebar with links. I think it is confusing to have two separate navigation points. There are few enough of them that I think they'd be better off in the top bar, unless the plan is that there will be many more pages in the future. The Wiki is listed in both places, so it'd only be two more items for the top bar.

**Comment by wd15** [comment]
@stvdwtt, ok, should I have a drop down (with scroll bar) for the wiki pages in the navbar.

**Comment by stvdwtt** [comment]
@wd15 That sounds perfect.

**Comment by wd15** [comment]
@tkphd, yes, it includes the prose pull request as well. I want to make more of the pages markdown rather than javascript or liquid syntax based so that anyone can edit it.

**Comment by tkphd** [comment]
The thing on the left looks just like what you see on Wikipedia, so it must be right.
I would suggest modifying it like so, with a Wikipedia-grey background:

> ## Wiki
> Main Page
> Phase-field Lectures
> Workshop Info

**Pull request merged**
