### PR TITLE
Add presentations from workshop 7 to wiki

### PR DESCRIPTION
**Pull request by wd15**
Address #882

Uploaded presentations to slideshare and link with iframe in wiki page

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-884.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/884)

### CODE REVIEW

**Comment by tkphd** [comment]
@guyer, would appreciate your thoughts on this.

**Comment by guyer** [comment]
I'm inclined to agree with @tkphd about the personal slideshare account.

FWIW, slide presentations by NIST staff must be ERBed before being posted to the public.

**Comment by guyer** [comment]
Having now churned through more than a few pull requests of both my own and others, I don't think it's either correct or valuable to "assign" to reviewers. Reviewers get notified that they've been asked to review. The fact that I did not review in a timely fashion was not altered by it being "assigned" to me.

**Comment by tkphd** [comment]
I agree in the abstract, but for a project with few reviewers and sparse feedback like this one, I find it helpful to use the "assign" feature like a [talking stick](https://en.wikipedia.org/wiki/Talking_stick), explicitly declaring who's responsible for progress on the PR. This probably made more sense when there was only one reviewer.

Perhaps it's best moving forward to let reviewers *self-assign*, instead of throwing the stick at them while they're not looking, and to have the relevant party un-assign themself when their job is completed.

**Comment by wd15** [comment]
I emailed Begum regarding setting up CHiMaD Slideshare account and waiting on that now.

**Comment by wd15** [comment]
@tkphd, @guyer, I set up a PFHub Slideshare account and pushed the presentations there. I hope that is adequate. Please review.

**Pull request merged**
