### PR TITLE
benchmark: adding SymPhas benchmark 7a

### PR DESCRIPTION
**Pull request by MetricManifold**
Adding SymPhas results for benchmark 7a.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1317)

### CODE REVIEW

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1317.surge.sh) is ready for review.

**Comment by MetricManifold** [comment]
@wd15 Travis build is failing due to "symphas" pattern not available in code names.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1317.surge.sh) is ready for review.

**Comment by wd15** [comment]
@MetricManifold: this looks good to me. Can you check [this](https://random-cat-1317.surge.sh/simulations/7a.0/) and [this](https://random-cat-1317.surge.sh/simulations/display/?sim=SymPhas_7a_CS_5pt) and make sure the results look correct / acceptable (nothing unexpected)? Thanks for the upload!

**Comment by MetricManifold** [comment]
> @MetricManifold: this looks good to me. Can you check [this](https://random-cat-1317.surge.sh/simulations/7a.0/) and [this](https://random-cat-1317.surge.sh/simulations/display/?sim=SymPhas_7a_CS_5pt) and make sure the results look correct / acceptable (nothing unexpected)? Thanks for the upload!

@wd15 I checked and everything looks good, thank you for confirming!

**Review by tkphd — APPROVED** [review]
@MetricManifold says it's good to go, and it looks good to me.

**Pull request merged**
