### PR TITLE
Generate comparison results from a template with Papermill

### PR DESCRIPTION
**Pull request by wd15**
Things done:

 - Only addresses BM1 so far 
 - Add new template notebook for BM1
 - Remove wd15/nixes dependency
 - Fix a few meta.yaml with broken urls and other syntax
 - Makefile to build notebooks in results/ directory
 - Auto generated notebooks for BM1a, b c

Todo:

 - [x] BM1d
 - [x] Ensure that markdown is updated appropriately

### CODE REVIEW

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1482.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1482.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1482.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1482.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1482.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1482.surge.sh

**Comment by wd15** [comment]
@tkphd: this is ready for your review now. Thanks!

**Review by tkphd — COMMENTED** [review]
Files look good, on to the notebooks ...

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1482.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1482.surge.sh

**Comment by wd15** [comment]
@tkphd, the table should look better now. Please review again. Thanks.

**Review by tkphd — CHANGES_REQUESTED** [review]
The new table looks much better! Some quibbles:

* The "Benchmark ID" column is redundant, since only submissions matching the caption (1a.1) are rendered
* Make Timestamp the first column, and sort reverse-chronologically (most recent first)
* Set Author and GitHub ID columns adjacent; consider dropping GitHub ID, since it's less important and captured on the upload detail page
* New table layout would be  
  `Timestamp Name Code Author GitHubID`

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1482.surge.sh

**Review by tkphd — APPROVED** [review]
Beautiful!

**Pull request merged**
