### PR TITLE
PFHub Upload: FBE_space

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload

To review:

- Wait for the tests to pass.

- Go to http://random-cat-769.surge.sh/

| Field     | Content                                                         |
| --------- | --------------------------------------------------------------- |
| metadata  | [object Object]                                                 |
| benchmark | [object Object]                                                 |
| data      | [object Object],[object Object],[object Object],[object Object] |
| date      | 1519415072                                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/769)

### CODE REVIEW

**Comment by wd15** [comment]
@narutse, thanks for your submission to PFHub. You've uploaded a result for problem 1a as specified, [here](https://pages.nist.gov/pfhub/benchmarks/benchmark1.ipynb/). The only requirement is that the free energy against time is uploaded. Please amend the meta.yaml by adding the free energy versus time data. If you have trouble amending the meta.yaml, then please just point me to the data in a comment here.

**Comment by wd15** [comment]
@narutse, problem 1a is just a single simulation not multiple simulations.

**Comment by narutse** [comment]
Thank you for the response. I think I uploaded for the wrong problem. I
meant to do it for the MMS one (problem 7). I'm sorry for that and will
reupload for correct problem.

**Comment by wd15** [comment]
@narutse: no worries. It's not easy to get right and the website is still under development. I'll just need to work with you on the pull request to get things right. Please do keep uploading.

When I've looked at all the data and built the images, I'll ping you again in this pull request for your final approval.

**Comment by narutse** [comment]
Thanks! I can see my results in the site now. I have time convergence data as well. Should I make another submission or is there a way to merge it with the old submission somehow?

**Comment by wd15** [comment]
@narutse you can do any of the following depending on what you're comfortable with 

 - edit the [meta.yaml](https://github.com/usnistgov/pfhub/blob/master/_data/simulations/FBE_space/meta.yaml#L26) directly for this entry to point at your new data. The data entry name needs to be `temporal`.

 - let me know the location of the data as a comment in this pull request and I can take care of it

 - click on "Use as Template for New Submission" button on this page, https://pages.nist.gov/pfhub/simulations/display/?sim=FBE_space, and then add the data. Remember to call it `temporal` and ensure that it's properly formatted CSV with no spaces after the commas and give the link for the raw version on GitHub.

**Comment by narutse** [comment]
I made a new submission here with both spatial and temporal data included: https://github.com/usnistgov/pfhub/pull/770
Modified the name and summary to be more descriptive. (You can remove the old version if the new one gets approved.) Thanks!

**Pull request merged**
