### PR TITLE
fix code name for meumapps upload

### PR DESCRIPTION
**Pull request by stvdwtt**
Fix the "name" field for the code, which is not actually the same as my name.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1241)

### CODE REVIEW

**Comment by pfhub** [comment]
@, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1241.surge.sh/simulations/display/?sim=

and

 - https://random-cat-1241.surge.sh/simulations/

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1241.surge.sh/simulations/upload_form/?sim=).

**Comment by wd15** [comment]
@stvdwtt I'll try and clean this up and get the test working and then ask for your approval. Please close #1240 if (I'm assuming) this supersedes that.

**Comment by stvdwtt** [comment]
Thanks!

You're correct that this supersedes #1240. However, it doesn't look like I have the permission to close PRs that aren't associated with my account.

**Comment by wd15** [comment]
@stvdwtt: scrub the last message. I see that you want to merge this into the other branch. Don't close #1240!

**Comment by pfhub** [comment]
@, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1241.surge.sh/simulations/display/?sim=

and

 - https://random-cat-1241.surge.sh/simulations/

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1241.surge.sh/simulations/upload_form/?sim=).

**Pull request merged**
