### PR TITLE
upload: zenodo.7474506

### PR DESCRIPTION
**Pull request by pfhub**
adding upload from issue #1477

what's been done:
 - Adjusted surge deployment so that the actual branch in the PR is deployed. Previously, the master branch was deployed. This was an oversight when setting up the original Surge deployment.
 - Set up data template for BM1a
 - Fixed some bugs in zenodo.py
 - Added a new test upload from Zenodo
 - Found a fix for a local problem with Jupyter config files getting out of sync
 - Fixed a dead link in a notebook
 - Use logging module to display error messages when debugging
 
todo:
 - [ ] check that Surge is taken down on merging this PR
 - [x] check that images actually show up
 - [x] remove [errors from notebook](https://random-cat-1478.surge.sh/results/benchmark1a.1.ipynb/)

### CODE REVIEW

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by pfhub** [comment]
@pfhub, the new version of the PFHub website is available at https://random-cat-1478.surge.sh

**Comment by wd15** [comment]
@tkphd, this is ready for you to review now

**Review by tkphd — APPROVED** [review]
LGTM. Shame about the dead Etherpad, wonder if anybody copied it ...

**Comment by wd15** [comment]
> LGTM. Shame about the dead Etherpad, wonder if anybody copied it ...

We should have copied it to the Wikipedia. Let's ensure we do that when we use similar tools in future.

**Pull request merged**
