### PR TITLE
Add 3a MOOSE INL benchmark

### PR DESCRIPTION
**Pull request by dschwen**
Doing a traditional PR. The static man thingie is driving me mad.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/876)

### CODE REVIEW

**Comment by dschwen** [comment]
So @wd15 it looks like for manual PRs there is no comment with the preview site location?

Here is the preview: https://random-cat-876.surge.sh/simulations/display/?sim=inl_moose_3a

And I managed to screw up that danged contour line again. Well at least I can now just fix my PR and push again.

**Comment by dschwen** [comment]
Yes, 67s on 6 cores on an MacPro trashcan (2.7GHz, >4 years old now). The already uploaded MOOSE results for this benchmark are quite misleading. Dong-Uk is using PJFNK, but this problem does not benefit from the larger time steps it allows for (and he  severely limits the time step anyhow). Ian's benchmark is a lot better, but he accidentally reported virtual memory rather than physical memory. 
I have to question the value of encouraging complete newbies uploading "benchmarks". If anything it can lead to dangerously misleading claims about relative code performances.

**Comment by dschwen** [comment]
Btw. the manual upload instructions (not that I read them before submitting this PR :-D) at https://pages.nist.gov/pfhub/simulations/upload/ do not mention any step that would update the JSON plot stuff.

**Comment by wd15** [comment]
@dschwen, I'm going to implement tags, labeling, stars etc so that we can label results that have somehow been given the seal of approval. Rather than limiting uploads, we can make the default display with the best results (assuming we can assess those).

**Comment by wd15** [comment]
@dschwen, editing the JSON is not necessary for the upload. It's something I do before pushing the final results with "make simulations". This step will be removed in future versions and all done on the frontend. Basically, don't worry about it.

**Comment by wd15** [comment]
@dschwen, are you basically happy now for me to merge this?

  - https://random-cat-876.surge.sh/simulations/display/?sim=inl_moose_3a
  - https://random-cat-876.surge.sh/simulations/3a.1/

All looks good to me.

**Comment by dschwen** [comment]
Yes. This is ready.

**Pull request merged**
