### PR TITLE
[WIP] CoRR v0.2 integration with PFHub

### PR DESCRIPTION
**Pull request by faical-yannick-congo**
**Details**
This pull request contains the first layer of work done on integrating CoRR and PFHub.
In this integration, PFHub is represented as a CoRR tool. However, since it is a web application 
that lives on its own, special requirements was to be fulfilled. The biggest of those was authentication and security regarding how PFHub users gets authorized to submit their simulation metadata to CoRR.
This is solved through the Github SSO. Thus, PFHub users gets redirected to GitHub where they must have an account and allow CoRR to fetch its info and assign it a temporary token to push content.
All content pushed in PFHub appear as CoRR records in specific projects moderated in CoRR by the PFHub tool moderator.
This pull request also provides a file upload feature along side url based uploads.
Raw file uploads such as data and media are stored in CoRR and are accessible through public links.

**In Summary:**

- SSO through Github
- User GitHub info automatically filled in the upload form.
- File uploads in addition to url based ones. For data/media items, user can choose between any of these two.
- Hackatons are CoRR projects that can be pulled from CoRR.
- Simulations are CoRR records that can be pulled from CoRR.
- PFHub tool moderator in CoRR has control over the content submitted by the users.
- Users do not have to be aware of CoRR. The interaction with CoRR as been made passive. Everything related to CoRR is either hidden in the view or a automated backend call

**Current issues to be fixed:**

- Cors issues that are random between CoRR, PFhub and Github: under assessment.
- Meta.yaml update with regards to CoRR raw files uploads.
- Table display and plots are kept as is and could be adjusted.
- Github throws Rate Limit issue on new users authentication from time to time.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-982.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/982)

### CODE REVIEW

**Comment by dschwen** [comment]
CoRR = [Computing Research Repository](https://arxiv.org/corr)

**Comment by wd15** [comment]
@faical-yannick-congo, why didn't the tests run?

**Comment by tkphd** [comment]
In this case, CoRR = [Cloud of Reproducible Records](https://corr.readthedocs.io/en/v0.2/rst/README.html).

**Comment by tkphd** [comment]
@wd15, it won't build due to the merge conflict. We deleted `_include/simulations.html`, and @faical-yannick-congo modified it, so Git is confused. [PR issued.](https://github.com/faical-yannick-congo/pfhub/pull/1)

**Comment by wd15** [comment]
@faical-yannick-congo, if you merge Trevor's PR then this will at least show the new upload form when it's built.

**Comment by faical-yannick-congo** [comment]
Hi @wd15 , @tkphd 
I merged Trevor's PR.

**Comment by wd15** [comment]
@faical-yannick-congo, I just did an [upload](https://github.com/usnistgov/pfhub/pull/985), however, I didn't need to authorize on CoRR first. Should I be promoted to do that?

**Comment by faical-yannick-congo** [comment]
@wd15, I saw your upload on GitHub. It shows usage of the new upload form (file and url types) in the meta.yml. I am not able to pin point to the error. As there is no server log saying that an error occurred.
However, I should mention that when you access PFHub page you should authorize the GitHub popup.
I think this might be the reason why your upload worked but the CoRR process was bypassed. I think this is worth pointing to the PFHub user/contributors. They need to be aware of and authorize the popup window to be taken to the GitHub page which should look like the following:

Screen Shot 2019-04-23 at 9 32 54 PM

This is the CoRR OAuth App on Github looking to verify their identity on GitHub in exchange for a temporary access that PFHub will then use to be authorized to push the upload and its files to CoRR.
Moreover, they will be taken to the corr-root.org instance but at this point the window will be closed automatically and the PFHub window refreshed to integrate the authorization. This process only happens once (during the agreement step). Later the process is seamless.
Do you mind trying another upload and following this?
Also if you could inspect the web page and share the console logs that would be fantastic for debugging.

**Comment by wd15** [comment]
@faical-yannick-congo,I didn't get a pop up!

**Comment by wd15** [comment]
I'm doing this on the Surge instance.

**Comment by wd15** [comment]
@faical-yannick-congo: I'm closing this for now. We can reopen if we ever take it up again.

**Pull request closed without merging**
