### PR TITLE
hrefs and pngs

### PR DESCRIPTION
**Pull request by tkphd**
- Replace hot-linked images with statically served versions
- Add `href` tags around institutions, codes, and projects
- Update affiliations for members in flux
- Harmonize language across profiles

Addresses #508, #564, #589.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/678)

### How to Review
These changes can be viewed [live](http://random-cat-678.surge.sh/community/).
- Check that you like the look and feel of the Community page.
- Confirm that your name is spelled correctly.
- Confirm that your e-mail address and networking buttons are correct.
- Read your biographical sketch.

#### Remember to tear down the [live site](http://random-cat-678.surge.sh/) when merging or closing this pull-request.

### CODE REVIEW

**Comment by tkphd** [comment]
Are we going to be pedantic about that, @wd15? (The changes are content, not code, so the template was not a good fit.)

**Comment by tkphd** [comment]
*edited to insert live test site links and teardown reminder*

**Comment by wd15** [comment]
@tkphd, you need to resolve some conflicts on this one.

**Comment by tkphd** [comment]
@wd15, thanks -- resolved.

**Pull request merged**
