### PR TITLE
PFHub Upload: moose_1b_jah

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

| Field     | Content                                         |
| --------- | ----------------------------------------------- |
| metadata  | [object Object]                                 |
| benchmark | [object Object]                                 |
| data      | [object Object],[object Object],[object Object] |
| date      | 1536778599                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/843)

### CODE REVIEW

**Comment by wd15** [comment]
@jah5759, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-843.surge.sh/simulations/display/?sim=moose_1b_jah

and

 - https://random-cat-843.surge.sh/simulations/1b.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

You can make further changes to this pull request by [editing the meta.yaml](https://github.com/usnistgov/pfhub/edit/staticman_948330e0-b6bd-11e8-a524-7dde27d5fbc0/_data/simulations/moose_1b_jah/meta.yaml?pr=%2Fusnistgov%2Fpfhub%2Fpull%2F843) associated with this pull request.

**Comment by jah5759** [comment]
@wd15 thanks for the info! I'm happy to edit them, but when I go to the file, it says that I need to have push access to edit it.  Am I missing something?  Thanks!

**Comment by wd15** [comment]
@jah5759, are you saying that this link doesn't work for you?

https://github.com/usnistgov/pfhub/edit/staticman_948330e0-b6bd-11e8-a524-7dde27d5fbc0/_data/simulations/moose_1b_jah/meta.yaml?pr=%2Fusnistgov%2Fpfhub%2Fpull%2F843

If not I need to find the link that lets users fork and edit.

**Comment by wd15** [comment]
What happens when you go to https://github.com/usnistgov/pfhub/pull/843/files and click the little edit button next to "View"? That works for you. What is that link? Can you copy and paste it into the comments. Thanks.

**Comment by jah5759** [comment]
The second link you sent is what I tried originally.  The edit button is grayed out and it says that I need push access to edit that way.  I am using the first link you sent to try to fork and edit now.

**Comment by wd15** [comment]
@jah5759, sorry for the difficulties. I'm still working on refining the process and getting it to be more seamless. Your feedback and help on this is appreciated.

**Comment by jah5759** [comment]
No problem.  I'm still getting used to git as well.  I edited the file using the fork method, but it's only updated on my fork.  Should I create a new pull request from the edited branch on my fork, or is there a way to attach it to this one?

**Comment by wd15** [comment]
@jah5759, it's a shame that it didn't work correctly. It's too complicated for you to edit all the files and then do separate pull requests (it's possible, but you shouldn't have to go through that pain). I'll think about how to let people more easily edit the meta.yaml files in the future. You'll get pinged when all the uploads are ready for review.

**Comment by jah5759** [comment]
@wd15 thanks for all your help!  Please let me know if there's anything else I can do in the mean time.

**Comment by wd15** [comment]
@jah5759, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-843.surge.sh/simulations/display/?sim=moose_1b_jah

and

 - https://random-cat-843.surge.sh/simulations/1b.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

You can make further changes to this pull request by [editing the meta.yaml](https://github.com/usnistgov/pfhub/edit/staticman_948330e0-b6bd-11e8-a524-7dde27d5fbc0/_data/simulations/moose_1b_jah/meta.yaml?pr=%2Fusnistgov%2Fpfhub%2Fpull%2F843) associated with this pull request.

**Comment by jah5759** [comment]
@wd15 looks good, thanks!

**Pull request merged**
