### PR TITLE
upload: fipy_8b

### PR DESCRIPTION
**Pull request by wd15**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

| Field     | Content                                                                         |
| --------- | ------------------------------------------------------------------------------- |
| metadata  | [object Object]                                                                 |
| benchmark | [object Object]                                                                 |
| data      | [object Object],[object Object],[object Object],[object Object],[object Object] |
| date      | 1571854498                                                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1065)

### CODE REVIEW

**Comment by wd15** [comment]
@guyer, is this a real upload? Is this a replacement for fipy_8a

**Comment by guyer** [comment]
Yes, it's a real upload. The realtime interactivity is overwhelming.

**Comment by tkphd** [comment]
Rebased for d955a77.

**Comment by wd15** [comment]
@guyer, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-1065.surge.sh/simulations/display/?sim=fipy_8b

and

 - https://random-cat-1065.surge.sh/simulations/8b.0

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1065.surge.sh/simulations/upload_form/?sim=fipy_8b).

**Comment by wd15** [comment]
@guyer, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-1065.surge.sh/simulations/display/?sim=fipy_8b

and

 - https://random-cat-1065.surge.sh/simulations/8b.0

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1065.surge.sh/simulations/upload_form/?sim=fipy_8b).

**Comment by wd15** [comment]
@guyer, this LGTM, the log plot is messed up as it is negative on the individual landing page, but this will be fixed with #1066

**Pull request merged**
