### PR TITLE
Create meta.yaml

### PR DESCRIPTION
**Pull request by sqmonismith**
benchmark results for MEMPHIS 6a

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1321)

### CODE REVIEW

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1321.surge.sh) is ready for review.

**Comment by wd15** [comment]
Hi @sqmonismith: thanks for the upload! Can you check the results on the test server? Here,

https://random-cat-1321.surge.sh/simulations/6a.0/

and

https://random-cat-1321.surge.sh/simulations/display/?sim=memphis_6a

Ensure the data represents your result fairly. Take a look at run times and memory usage for example.

Two questions.

 - Was the simulation executed on a single node and single core as stated in the YAML file? I'm guessing it wasn't.
 - What architecture did you use for this? [Here's a list to choose from.](https://github.com/usnistgov/pfhub/blob/master/_data/simulations/example/schema.yaml#L114)
 - Can you ensure the [hardware section in the YAML file](https://github.com/usnistgov/pfhub/blob/5a91a57aac7684364d41887a50c1cf76cbaedefa/_data/simulations/memphis_6a/meta.yaml#L37) is correct.

Feel free to just drop the values in the conversation here and I can update the YAML file.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1321.surge.sh) is ready for review.

**Comment by tkphd** [comment]
Free energy evolution & memory/time plots look perfectly in line.

**Comment by sqmonismith** [comment]
@wd15 , I checked the results on the pfhub site and they look correct, thanks!  We did, indeed, run on a single node/single core.  I am trying to find more information about the hardware & architecture but the Tufts HPC confluence page is a little sparse.  I'll reach out to our admins and see if they can provide a bit more information.

**Comment by wd15** [comment]
@sqmonismith: I'm going to merge this. We can update it if you can gather more data regarding the hardware.

**Pull request merged**
