### PR TITLE
Issue753 docker nix

### PR DESCRIPTION
**Pull request by wd15**
Address #753

Nix and Docker builds for PFHub. This change makes developing and deploying the website much easier.

To review this, please install Nix and run `nix-shell` and go through the steps outlined in [NIX.md](https://github.com/wd15/pfhub/blob/issue753-docker-nix/NIX.md). Also go through the steps outlined in [DOCKER.md](https://github.com/wd15/pfhub/blob/issue753-docker-nix/DOCKER.md). Please identify issues with the documentation. It's probably too sparse right now.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-786.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/786)

### CODE REVIEW

**Comment by laagesen** [comment]
Hi @wd15, I tried to set this up but I'm having some trouble when trying to run `nix-shell`. I installed nix using the instructions at `https://nixos.org/nix/download.html`. The installer seems to have run successfully. However, when I tried to look at the Nix notes you linked to at
https://github.com/wd15/nixes/NIX-NOTES.md
I got a "Not found" page. So I tried skipping ahead to cloning the pfhub repo and running `nix-shell` there, but I got an error message
`error: getting status of '/Users/aagelk/projects/pfhub/default.nix': No such file or directory`
I'm guessing there may be something I missed since I wasn't able to see the NIX-NOTES file.

**Comment by wd15** [comment]
@laagesen, I checked `nix-shell` with `nix-shell (Nix) 2.0` and it also finds the `nix.shell` file by default. My guess is that you were on the wrong branch unless you have an older version of Nix.

**Comment by laagesen** [comment]
@wd15, you were right about not being on the right branch. Also for the benefit of anyone else doing this, after installing nix I had to do a full reboot in order for nix-shell to connect to the nix daemon as was discussed here:

https://github.com/NixOS/nix/issues/1980

And now I can begin the build with either `nix-shell shell.nix` or `nix-shell`. So now the build begins but has the following error, any suggestions what could be going wrong?

builder for '/nix/store/wb245w7rpa1z4gjknsm6dpgs6axxbc6s-python3.6-selenium-3.6.0.drv' failed with exit code 127
cannot build derivation '/nix/store/hk0g7h6lvbsax3qnk5616wz4wr35hqfw-python3.6-bokeh0.12.14.drv': 1 dependencies couldn't be built
error: build of '/nix/store/21kqj6hwa3mvklx2yzw53hfvzg7anl21-node-mocha-5.1.0.drv', '/nix/store/6n9fzsy6iks2xlvvs2gj78z6yqccwva6-python3.6-progressbar2-3.34.3.drv', '/nix/store/73ra12lybbp67fvmzf8xvjkjz8pzf06q-python3.6-nbval-0.9.0.drv', '/nix/store/8hy1hpi21k1labb4cfzgylbl15xjg568-jekyll_env.drv', '/nix/store/8z81yf7cy62jrdxxpwyyh2p76vkhxfwj-python3.6-vega-0.5.0.drv', '/nix/store/cfc1y3icsdzxxmmdl3c1h80k587achkf-python3.6-jupyter-1.0.0.drv', '/nix/store/gq5gpvm6g4rzf869r2dvq8dc9nr8hy3l-pfhub.drv', '/nix/store/hk0g7h6lvbsax3qnk5616wz4wr35hqfw-python3.6-bokeh0.12.14.drv', '/nix/store/kc2aqp5m7p2qrfgfiwqynhqh660nyvh7-python3.6-pykwalify-1.6.0.drv', '/nix/store/l7zpd2dcdskkkhqhyfcg814qs87hjc66-node-coffeelint-2.1.0.drv', '/nix/store/vam6g6zqxn92bzwdylh8701jsljwmkwm-node-execjs-1.0.7.drv', '/nix/store/w8q1flj1mdm97qabbfdrp12agpd642ym-node-surge-0.20.1.drv', '/nix/store/wb6kqy5qybjz36fssnn300sfy0ag63ak-node-assert-1.4.1.drv' failed

**Comment by wd15** [comment]
@laagesen, my guess is that it is another Mac OS issue. I'll need to have @guyer give it a go and see if the same error arises. Thus far, I've tested on two linux machines, Docker and Travis CI so the Mac OS differences seem the most likely culprit. If you're interested in debugging, you can start commenting out packages in this [list](https://github.com/wd15/pfhub/blob/issue753-docker-nix/_nix/build.nix#L16) using `#`. I would start with `python36Packages.bokeh` judging from the error message above.

**Comment by laagesen** [comment]
OK thanks @wd15 - since it sounds like it may be OS related - I need to upgrade the OS on this machine anyway so I think I will give it another try after the upgrade before trying to troubleshoot the current error.

**Comment by guyer** [comment]
@laagesen @wd15 I get the same error on Sierra (10.12.6 (16G1314)).

I note that I did not need to reboot before I could connect to the nix daemon.

**Comment by guyer** [comment]
I note before the selenium/bokeh failure, I get:

    /nix/store/0igxxngigjgfkgg3cw547n92b8bpg6b1-stdenv-darwin/setup: line 1231: gcc: command not found


[this](https://github.com/NixOS/nixpkgs/issues/26720) might be relevant?

**Comment by guyer** [comment]
Commenting out `bokeh` in `_nix/build.nix` leads to failures in `notebook`:

    OSError: Insufficient access privileges for operation

Commenting out `jupyter`, too, gets functional `nix-shell`

**Comment by wd15** [comment]
@guyer, I added a shell-osx.nix file for installing on OS X. It simply doesn't install Jupyter and Bokeh.

**Pull request merged**
