### PR TITLE
PFHub Upload: moose_2a_xueyang94

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

| Field     | Content                                         |
| --------- | ----------------------------------------------- |
| metadata  | [object Object]                                 |
| benchmark | [object Object]                                 |
| data      | [object Object],[object Object],[object Object] |
| date      | 1549930356                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/932)

### CODE REVIEW

**Comment by wd15** [comment]
@xueyang94, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-932.surge.sh/simulations/display/?sim=moose_2a_xueyang94

and

 - https://random-cat-932.surge.sh/simulations/2a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-932.surge.sh/simulations/upload_form/?sim=moose_2a_xueyang94).

**Comment by dschwen** [comment]
Wow, looks like you got it about 10000x faster. Nice!

**Comment by wd15** [comment]
@xueyang94, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-932.surge.sh/simulations/display/?sim=moose_2a_xueyang94

and

 - https://random-cat-932.surge.sh/simulations/2a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-932.surge.sh/simulations/upload_form/?sim=moose_2a_xueyang94).

**Comment by wd15** [comment]
@xueyang94, please confirm that you're happy with the upload.

**Comment by xueyang94** [comment]
@wd15 Yes the upload looks good. Thanks.

**Pull request merged**
