### PR TITLE
PFHub Upload: Tonks_MMS_results

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload

To review:

- Wait for the tests to pass.

- Go to http://random-cat-760.surge.sh/simulations/display/?sim=Tonks_MMS_results

| Field     | Content                                                         |
| --------- | --------------------------------------------------------------- |
| metadata  | [object Object]                                                 |
| benchmark | [object Object]                                                 |
| data      | [object Object],[object Object],[object Object],[object Object] |
| date      | 1519055018                                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/760)

### CODE REVIEW

**Comment by tkphd** [comment]
@wd15, any way to get accessible links from DropBox?

**Comment by wd15** [comment]
@tkphd, I believe that Dropbox should work, see https://www.dropbox.com/help/desktop-web/force-download

@tonkmr, right now the data files have no headings so it's not possible to read the CSV file. The Vega loader, I think, requires that the CSV files have labeled headers. So, for example your data file should be,

```
dt, L2
0.0325,0.0005612
0.0625,0.0005614
0.125,0.00056229
0.25,0.00056723
0.5,0.00060516
```

for example. At the moment, I think the `dt, L2` is missing. Unfortunatly, Vega doesn't seem to be clever enough to infer the x and y axes.

**Comment by wd15** [comment]
@tkphd, furthermore, one can avoid the CORS issue on Dropbox by using `dl.dropboxusercontent.com`, see https://www.dropboxforum.com/t5/API-support/CORS-issue-when-trying-to-download-shared-file/m-p/82470/highlight/true#M2431

**Comment by tonkmr** [comment]
The linked files now have headers

**Comment by wd15** [comment]
@tonkmr, sorry, another issue. CSV files can't have spaces in the header (at least the spec for D3). That's my fault as I posted the wrong header above. Sorry, So try this,
```
dt,L2error
0.0325,0.0005612
0.0625,0.0005614
0.125,0.00056229
0.25,0.00056723
0.5,0.00060516
```
We're almost there. It's reading the x-values correctly, but I'm getting null values for the y data.

**Comment by wd15** [comment]
@tonkmr, please give your approval and then I'll merge.

http://random-cat-760.surge.sh/simulations/7a.0/

**Pull request merged**
