### PR TITLE
PFHub Upload: moose_1c_xueyang94

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

| Field     | Content                                         |
| --------- | ----------------------------------------------- |
| metadata  | [object Object]                                 |
| benchmark | [object Object]                                 |
| data      | [object Object],[object Object],[object Object] |
| date      | 1549383735                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/930)

### CODE REVIEW

**Comment by dschwen** [comment]
The title of this benchmark is very nondescript. I'd rather have it be the name of a code and/or an institution (not "chimad")

**Comment by wd15** [comment]
@xueyang94, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-930.surge.sh/simulations/display/?sim=chimad1_c

and

 - https://random-cat-930.surge.sh/simulations/1c.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-930.surge.sh/simulations/upload_form/?sim=chimad1_c).

**Comment by tkphd** [comment]
@xueyang94, thanks for the upload! If you look at thye second link @wd15 sent, your data gets labeled *chimad_1c* in the legend. This does not really fit with the rest of the datasets, which dev teams tend to name after their code (MOOSE, FiPy) and individuals tend to name after their institutions (INL). Would you agree to renaming your upload from **chimad_1c** to **ufl_moose_1c**?

**Comment by xueyang94** [comment]
@tkphd I'll rename the upload. Also in the second link @wd15 sent, my result isn't in the Free Energy vs Time plot. In this link [https://random-cat-930.surge.sh/simulations/display/?sim=chimad1_c] my plot doesn't have the correct x and y axis names. In the upload form Data Files session, the name of x and y axis columns refer to the column name in my .csv file I believe. So where should I set the axis name for the plot?

**Comment by wd15** [comment]
@xueyang94, don't worry, I'm fixing the data in the Free Energy vs Time plot. I can also rename this entry. What would you like to call it?

**Comment by xueyang94** [comment]
@wd15 yes please. Thank you.

**Comment by wd15** [comment]
@xueyang94, what new name would you like for the entry? What about `moose_1c_xueyang94"?

**Comment by xueyang94** [comment]
@wd15  `moose_1c_xueyang94' sounds good but is the entry the same thing as the upload title? Some people above suggest ufl_moose_1c. I'm a little confused.

**Comment by wd15** [comment]
@xueyang94, yes the "entry" is the same things as the "upload title". I would go with  `moose_1c_xueyang94` since it's more specific.

**Comment by xueyang94** [comment]
@wd15 'moose_1c_xueyang94' then. Thanks.

**Comment by wd15** [comment]
@xueyang94, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-930.surge.sh/simulations/display/?sim=moose_1c_xueyang94

and

 - https://random-cat-930.surge.sh/simulations/1c.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-930.surge.sh/simulations/upload_form/?sim=moose_1c_xueyang94).

**Pull request merged**
