### PR TITLE
upload: memphis_3a

### PR DESCRIPTION
**Pull request by wd15**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

upload: memphis_3a
benchmark_id: 3a.1
github_id: rdingre

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1167)

### CODE REVIEW

**Comment by pfhub** [comment]
@rdingre, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1167.surge.sh/simulations/display/?sim=memphis_3a

and

 - https://random-cat-1167.surge.sh/simulations/3a.1

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1167.surge.sh/simulations/upload_form/?sim=memphis_3a).

**Comment by rdingre** [comment]
Results look good.

**Comment by stvdwtt** [comment]
Hi @rdingre, thanks for your upload! Looking at your upload, it seems that your ordering for the points in the contour is a little off. If you look at it, you'll see that part of the plot looks "filled in". I'm guessing that you sorted the points by their y value. Unfortunately, for dendrites that the points aren't in the natural order to follow along the interface. Instead, you need to sort them by angle. I usually copy my (x,y) data into Excel and then add a third column that is something like arctan(y/x) to get the angle (...I think that trig is right, it's early in the morning), sort based on that, delete the angle column, and then save as a .csv.

Let me know if that doesn't make sense.

**Comment by wd15** [comment]
@rdingre: I'll try and fix this so that the website can reorder the points correctly. I thought that I had already made that work, but something obviously isn't right. However, if you can reorder the points (as @stvdwtt helpfully suggested) in the meantime then that would be handy.

**Pull request merged**
