### PR TITLE
Add GitHub ID to default display of table data

### PR DESCRIPTION
**Pull request by wd15**
Address #889

This is only for the notebook version of the comparison pages. All comparison pages will be switched over to notebook views eventually. Not addressing this in JS / CoffeeScript.

**Remember to tear down the live site when merging or closing this
pull request.**

### CODE REVIEW

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1424.surge.sh) is ready for review.

**Comment by tkphd** [comment]
In `results/benchmark8a.1.ipynb`:

```error
[Errno 2] No such file or directory: './data/8a-8a_0.99r-stats.txt' for ./data/8a-8a_0.99r-stats.txt 
[Errno 2] No such file or directory: './data/8a-8a_1.00r-stats.txt' for ./data/8a-8a_1.00r-stats.txt 
[Errno 2] No such file or directory: './data/8a-8a_1.01r-stats.txt' for ./data/8a-8a_1.01r-stats.txt
```

The free energy and solid interface plots for $r = 0.99 r_0$ are not populated; the rest have at least one curve, despite the error messages.

**Comment by wd15** [comment]
> In `results/benchmark8a.1.ipynb`:
> 
> ```
> [Errno 2] No such file or directory: './data/8a-8a_0.99r-stats.txt' for ./data/8a-8a_0.99r-stats.txt 
> [Errno 2] No such file or directory: './data/8a-8a_1.00r-stats.txt' for ./data/8a-8a_1.00r-stats.txt 
> [Errno 2] No such file or directory: './data/8a-8a_1.01r-stats.txt' for ./data/8a-8a_1.01r-stats.txt
> ```
> 
> The free energy and solid interface plots for r=0.99r0 are not populated; the rest have at least one curve, despite the error messages.

Sorry! This should have had WIP on it. I hadn't finished.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1424.surge.sh) is ready for review.

**Comment by tkphd** [comment]
No worries! The "WIP" is more trouble than it's worth, but it's good to see the "draft" property has been set.

**Comment by wd15** [comment]
Ok, this is ready for review now.

**Comment by wd15** [comment]
The failure is just from pypi timing out for a download when building the nix environment. This will pass as it passed before I rebased and nothing changed during the rebase.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1424.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1424.surge.sh) is ready for review.

**Pull request merged**
