### PR TITLE
Issue709 benchmark3 results

### LINKED ISSUE #709: Upload and display sensible results for problem 3
Ensure the comparison page shows relevant plots

### PR DESCRIPTION
**Pull request by wd15**
Fixes #709

 - Implement a comparison page for benchmark 3a.1
 - Use Plotly for charts. This will be done for all charts in the future. Will move away from using Vega. Much easier to implement using Plotly than with Vega.
 - Data for the new page is not processed in Python anymore

## Problems

I introduced some tests

https://github.com/usnistgov/pfhub/pull/746/files#diff-4f5ec6a110073cead11b70b974d54ffeR316

that require backend Javascript libraries. These work locally for me, but I can't get them installed correctly in Travis so I've commented out the tests for now and moved fixing this to #748.

Also, do we need some more narrative / explanation on the comparison pages. If so, maybe we could move this to another issue.

## Review

To review, see,

http://random-cat-746.surge.sh/simulations/3a.1/

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-746.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/746)

### CODE REVIEW

**Comment by wd15** [comment]
@stvdwtt, I've assigned you as a review on this as this page can be very quickly turned around for problem 7 if you're happy with it.

**Comment by wd15** [comment]
@stvdwtt, check it in Firefox. I need to fix it in Chrome.

**Comment by wd15** [comment]
It should work in Chrome now. I had to move the data to a GitHub Gist unfortunately. I need to investigate why Chrome is not working with data from Figshare. I've moved this to #751.

**Comment by stvdwtt** [comment]
I can verify that it works with Chrome and Safari now.

One last thing, there's what looks like an extraneous "3" at the end of the plot explanation text:
untitled

**Comment by wd15** [comment]
@stvdwtt, that text is all irrelevant now, it was for Vega. I'll delete it.

**Pull request merged**
