### PR TITLE
PFHub Upload: PRISMSPF_Quad_7b

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload

To review:

- Wait for the tests to pass.

- Go to http://random-cat-765.surge.sh/simulations/display/?sim=PRISMSPF_Quad_7b to review the upload

- Both results pages have been updated, see
   - http://random-cat-765.surge.sh/simulations/7b.0/
   - http://random-cat-765.surge.sh/simulations/7a.0/

| Field     | Content                                                         |
| --------- | --------------------------------------------------------------- |
| metadata  | [object Object]                                                 |
| benchmark | [object Object]                                                 |
| data      | [object Object],[object Object],[object Object],[object Object] |
| date      | 1519166075                                                      |
| approved  | false                                                           |
| title     | Comment                                                         |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/765)

### CODE REVIEW

**Comment by wd15** [comment]
@stvdwtt,I can fix the meta.yaml, but can you see if the CSV file is correct

**Comment by stvdwtt** [comment]
It looks like I linked to the wrong csv file. That file is for one of the part a datasets.

I’ll fix it up at some point today.

**Comment by wd15** [comment]
@stvdwtt, is this ok?

http://random-cat-765.surge.sh/simulations/7b.0/

What are the units supposed to be on the cost function?

**Comment by wd15** [comment]
On Thu, Mar 1, 2018 at 8:38 AM, Stephen DeWitt <notifications@github.com> wrote:
>
> The cost function units should be "Normalized Core Seconds".

Can we have that as symbols? We can define the symbols below the graph
and in the spec. Something like (s / s_n) or (s / N) or whatever it
is. Maybe also, define the cost function as F_c and define it in the
spec. Also I'll make the L2 Error to be just L_2 as long as we refer
to L_2 in the spec. Also, the wall time, let's choose a symbol for
that as well. I'll define all the symbols below the graph as well as
in the spec. Can you give me a list of what you would like as those
symbols? What's are the units for L2 Error?

> Do you have any control over the width of the comparison plots?

We have complete control over the width. Currently, the width resizes
to fit on the page, while the height remains constant for all sizes.
Would you prefer if a constant aspect ratio is maintained regardless
of page width or do we want to keep the graphs a constant pixel size
and have the users scroll to see the entire graph on a small screen.
What do you think?

-- 
Daniel Wheeler

**Comment by wd15** [comment]
@stvdwtt, also for 7a.0. Lets figure out the symbols and units. I'll do it all as part of this pull request.

**Comment by wd15** [comment]
I'm thinking $\Delta x$, $\Delta t$, $L_{2, \Delta x}$, $L_{2, \Delta t}$ for 7a and $t_{wall}$ and $c_{wall}$ for the cost function.

**Comment by wd15** [comment]
So, 2f4c4d6 still allows the graphs to autosize, but keeps a minimum width for all graphs of 500px. Let me know if you think that should be adjusted. That will require scrolling to see the entire graph on small screens, which my be difficult, not that we should worry about that too much.

**Comment by stvdwtt** [comment]
Great, the new minimum width looks great on both my workstation monitor and my phone.

As far as the axis labels go, $\Delta x$, $\Delta t$, and $t_{wall}$ sound good. I think $e_{L2}$ might be clearer for the error. For the cost function, I think we should stay away from "c" to avoid confusion with a composition/concentration variable. I think $f_{cost}$ could work.

**Comment by wd15** [comment]
@stvdwtt, @tkphd, @guyer: this is now ready for review

@guyer: I added you on this as you had complaints about the graphs for 7a. Graphs for 7a and 7b have been updated.

I have not been able to get Mathjax working with Plotly. It's supposed to work, but I have had no luck. I tried debugging, but seemed too difficult. Currently, I'm just using a combination of HTML and Unicode to make maths on the plotly graphs. I might try again in the future, but will have to do for now.

**Comment by wd15** [comment]
@stvdwtt, I fixed the units, please give your approval.

**Comment by ksmcreynolds** [comment]
I think the 2 & 5 minor markers on the y axis could be removed leaving just the powers of 10. They are roughly the same size as the exponents which leads a very cluttered look. That level of detail isn't really necessary since the exact values can be obtained by a mouseover.

**Comment by wd15** [comment]
@ksmcreynolds, thanks for the pointers, I made the changes. I added you as a collaborator on this project so when you approve I can also add you as a reviewer.

**Comment by wd15** [comment]
@ksmcreynolds, I added you as a reviewer, so please give a green tick if you get a chance (and if you approve the pull request of course!)

**Comment by wd15** [comment]
@guyer, @tkphd, please review this if you get a chance or remove yourself as a reviewer if you're too busy, thanks

@stvdwtt, please give the magic green tick if you get a chance, thanks

**Comment by stvdwtt** [comment]
@wd15 Not to rush/skip a review by @guyer, but would it be possible to merge this in today? I'm using 7b in my talk tomorrow and it'd be great to have the comparison page up for people to see.

**Comment by wd15** [comment]
@stvdwtt, merged now. Good luck with your talk!

**Comment by stvdwtt** [comment]
Thanks!

**Pull request merged**
