### PR TITLE
feat: adding SymPhas to codes

### PR DESCRIPTION
**Pull request by MetricManifold**
Adding the convergence test for the pfhub benchmark problem 7a.0, using the SymPhas software.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1315)

### CODE REVIEW

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1315.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1315.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1315.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1315.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1315.surge.sh) is ready for review.

**Comment by MetricManifold** [comment]
Validation with Travis CI build is failing because of file unassociated with the pull request.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1315.surge.sh) is ready for review.

**Comment by wd15** [comment]
@MetricManifold, thanks for this. Your code certainly looks really well put together. I'll let a few others take a look and hopefully have this merged in the next few days.

**Comment by wd15** [comment]
@tkphd @guyer: this PR wants to add a new code, see, the bottom of https://random-cat-1315.surge.sh/codes/

**Comment by wd15** [comment]
@MetricManifold: add your code on https://www.openhub.net/ if you'd also like that badge.

**Review by wd15 — APPROVED** [review]

**Comment by MetricManifold** [comment]
> @MetricManifold, thanks for this. Your code certainly looks really well put together. I'll let a few others take a look and hopefully have this merged in the next few days.

Thank you for the positive feedback and accepting SymPhas. I am happy to be able to add to PFHub and it's collection of PF codes.

**Comment by wd15** [comment]
> Thank you for the positive feedback and accepting SymPhas. I am happy to be able to add to PFHub and it's collection of PF codes.

Please do let me know if you need help adding results from SymPhas.

**Review by tkphd — APPROVED** [review]
Looks good! Happy to have another platform in the toolbox.

**Pull request merged**
