### PR TITLE
Added benchmark 1a YAML.

### PR DESCRIPTION
**Pull request by mfrichtl**
My metadata and solution for benchmark problem 1a.

### CODE REVIEW

**Comment by pfhub** [comment]
@mfrichtl, the new version of the PFHub website is available at https://random-cat-1481.surge.sh

**Comment by pfhub** [comment]
@mfrichtl, the new version of the PFHub website is available at https://random-cat-1481.surge.sh

**Comment by wd15** [comment]
@mfrichtl: thanks for the uploads! I need to push a few changes to your PR to clean things up. I'll let you know when I think it's ready and let you check it over before merging.

**Comment by pfhub** [comment]
@mfrichtl, the new version of the PFHub website is available at https://random-cat-1481.surge.sh

**Comment by wd15** [comment]
@mfrichtl: you can check your 1a simulation [here](https://random-cat-1481.surge.sh/results/benchmark1a.1.ipynb/). The free energy seems to be lower than other simulations. That's not a bad thing necessarily, but I wanted to let you know.

**Comment by wd15** [comment]
@mfrichtl: there are some issues with the 1b and 1c uploads that I'm repairing. I should be able to fix those in the next few days so will get back to you soon on this PR.

**Comment by mfrichtl** [comment]
Hi! Thanks for the help. I wasn't aware the 1b and 1c commits were in the PR. I was going to see if you had any comments on the 1a PR so that I could make sure I was formatting everything the right way. I also reran 1b yesterday because I discovered that I didn't have the BCs setup correctly and haven't pushed the new results yet.

Matt

-------- Original Message --------

**Comment by mfrichtl** [comment]
Interesting! I knew the general shape of my free energy vs. time curve was similar to other results, but couldn't tell that it was lower by just visually comparing them. Could be my timestepping strategy? I used an adaptive timestepper based on number of nonlinear solver iterations.

Matt

------- Original Message -------

**Comment by pfhub** [comment]
@mfrichtl, the new version of the PFHub website is available at https://random-cat-1481.surge.sh

**Comment by mfrichtl** [comment]
@wd15 I figured out the problem. I was only integrating the bulk free energy and not including the gradient energy. It looks like my results should be more in line with the rest after making the correction. I will re-run the models and push to my fork of the repo. If you can share with me what other fixes are needed with my submissions I can take care of those as well to save you the trouble. I should have looked more closely at my results compared to the others before issuing the PR.

**Comment by wd15** [comment]
No worries. This is the point of the pull-request to iron out the issues. There are always issues with uploading results.

Don't worry about the fixes too much. Use the meta.yaml that I've edited as the starting point. Maybe a new PR is a good idea for your new result. Also, seperate PRs for each upload (1a, 1b, and 1c) would be handy. Thanks!

Please do continue the uploads though. It's a great resource for other researchers to see different implementations from other codes.

> @wd15 I figured out the problem. I was only integrating the bulk free energy and not including the gradient energy. It looks like my results should be more in line with the rest after making the correction. I will re-run the models and push to my fork of the repo. If you can share with me what other fixes are needed with my submissions I can take care of those as well to save you the trouble. I should have looked more closely at my results compared to the others before issuing the PR.

**Comment by wd15** [comment]
@mfrichtl: Please feel free to close this if you  open PRs for the new results.

**Comment by pfhub** [comment]
@mfrichtl, the new version of the PFHub website is available at https://random-cat-1481.surge.sh

**Comment by pfhub** [comment]
Successful teardown of random-cat-1481.surge.sh

**Pull request closed without merging**
