### PR TITLE
fix: repair broken BM7.b charts

### PR DESCRIPTION
**Pull request by wd15**
Reestablish BM7.b and BM7.c charts, which got accidentally mauled
somewhere. Improve BM7 submission guidelines to address the names of
the data items and the format of the CSV files.

This PR was prompted by #1169 which had the correct data for the current graphs, but the current graphs are completely wrong for 7b.

A comment will appear below when the live site is built. This normally
takes a few minutes.

**Remember to tear down the live site when merging or closing this
pull request.**

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1173)

### CODE REVIEW

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1173.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1173.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1173.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1173.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1173.surge.sh) is ready for review.

**Comment by tkphd** [comment]
I'll defer to @stvdwtt on this one. From a back-end standpoint, it looks fine.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1173.surge.sh) is ready for review.

**Comment by wd15** [comment]
Right, I can't seem to find the commit where this reverted or a version that shows the correct plots for 7b, but I know I implemented that stuff at some point. Anyway, please check again. All should be good now.

> The updated charts look right for 7b, thanks for fixing that. I think we used to have a note on the page defining what "normalized computational cost" means. The description is in the spec, but I think it helps to have it on the results page as well to interpret the plot.
> 
> Something to the effect of:
> F_cost = wall time in seconds × number of cores × nominal core speed / 2 GHz
> 
> in text below the plot on the left.

**Pull request merged**
