### PR TITLE
PFHub Upload: moose_fh_1c

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload

To review:

- Wait for the tests to pass.

- Go to http://random-cat-{pull-request-number}.surge.sh/simulations/{simulation_name}

| Field     | Content                                         |
| --------- | ----------------------------------------------- |
| metadata  | [object Object]                                 |
| benchmark | [object Object]                                 |
| data      | [object Object],[object Object],[object Object] |
| date      | 1533845029                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/802)

### CODE REVIEW

**Comment by wd15** [comment]
@FHilty, please check that you're happy with the rendering of the results at

http://random-cat-800.surge.sh/simulations/display/?sim=moose_fh_1c

and

http://random-cat-800.surge.sh/simulations/1c.1/

and then I'll merge it. Thanks so much for your contribution!

**Comment by FHilty** [comment]
The links for this one and all benchmark 2 variants are taking me to a page saying that the simulation results has not been uploaded yet.

**Comment by wd15** [comment]
@FHilty, Sorry, I put the wrong link. This should be better

Please check that you're happy with the rendering of the results at

http://random-cat-802.surge.sh/simulations/display/?sim=moose_fh_1c

and

http://random-cat-802.surge.sh/simulations/1c.1/

and then I'll merge it. Thanks so much for your contribution!

**Comment by FHilty** [comment]
@wd15, looks good, thanks!

**Pull request merged**
