### PR TITLE
Add Stephen DeWitt's talk at TMS 2018

### PR DESCRIPTION
**Pull request by wd15**
Address #777

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-824.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/824)

### CODE REVIEW

**Comment by wd15** [comment]
See http://random-cat-824.surge.sh/wiki/2018-08-22-computational-performance-of-phase-field-calculations/ to review

**Comment by stvdwtt** [comment]
:+1:
Looks good to me, thanks for putting this up.

**Comment by tkphd** [comment]
> #### Wiki Pages
> Computational Per...
> PFHub Poster at M...
> Second Benchmark...
> Main Page
> Phase Field Lectures
> Workshops

does not look right. Can we 
* merge the "Computational Per" and "PFHub Poster at M" into a single "Presentations" page,
* reformat the presentation listing as a bibliography, with clear differentiation of the links as the Abstract and the Slides,
* Link "Steve DeWitt" to the PFHub Community Page, rather than a slideshare account,
* merge "Second Benchmark" into a "Publications" page with both (all) papers, and
* reorder the listing to keep Main Page at the top?

**Comment by tkphd** [comment]
I'm also not convinced that masking the Wiki from htmlproofer's judgment is the right approach.

**Comment by wd15** [comment]
@tkphd, regarding the htmlproofer issue. The only things that are masked, are the links to "history" and "source". This is because those links don't exist on GitHub until the branch is merged. There is no way around it as the page has no way of knowing which github org / repo / branch its associated with. This information comes from _config.yml.

**Comment by wd15** [comment]
@tkphd, wait, actually there is sort of a way which isn't as bad. Travis CI knows it is in pull request mode so I can change the htmlproofer mode based on whether it's a pull request.

**Comment by tkphd** [comment]
@wd15, can't wait to steal that code!

**Pull request merged**
