### PR TITLE
feat: benchmark 8 spec

### PR DESCRIPTION
**Pull request by wd15**
Full implementation of benchmark 8

Address #1208

Includes
 
 - automated citations using a new notebook extension
 - fix for equation numbering

This is really a draft as the submission guidelines may need to change based on some test uploads. The actual benchmark 8 landing page is not yet functional for this set of submission guidelines.

## TODO

 - [x] check this against the [overleaf document prepared by Wenkun](https://www.overleaf.com/project/6054d63507773a86652e22b5)
 - [x] Ensure link to "Phase Field Benchmark Problems for Nucleation" in notebook is correct
 - [x] Setup reviewnb
 - [x] Make phase field upload optional for 8a

**Remember to tear down the live site when merging or closing this
pull request.**

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1230)

### CODE REVIEW

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1230.surge.sh) is ready for review.

**Comment by wd15** [comment]
@tkphd this is the first draft of BM8. I probably need to modify it again if the paper has changed. I won't merge this until the paper goes to pre-print, but wanted to check that all the tests passed in a PR.

Also, we can test the upload guidelines when I get the BM8 results pages sorted in a separate PR

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1230.surge.sh) is ready for review.

**Comment by wd15** [comment]
@wuwenkun, please review this when you get a chance, I've compared with your latest overleaf version and it seems pretty good. Some of the ordering is a little different, but I'm not sure that matters.

**Comment by wd15** [comment]
@wuwenkun, this is the link for the notebook rendered on the website,

  https://random-cat-1230.surge.sh/benchmarks/benchmark8.ipynb/

and the link if you want to make changes to the notebook, 

https://github.com/wd15/pfhub/blob/issue1208-bm8/benchmarks/benchmark8.ipynb

**Comment by wd15** [comment]
@tkphd, could you take a look at this again. Also, feel free to say "no" to this if you can't face looking at this problem again. Thanks.

**Comment by tkphd** [comment]
It's a great problem! Happy to look!

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1230.surge.sh) is ready for review.

**Comment by tkphd** [comment]
Is a new reference available? The link labeled "Phase Field Benchmark Problems for Nucleation" goes to the dendritic growth paper.

**Comment by wd15** [comment]
> Is a new reference available? The link labeled "Phase Field Benchmark Problems for Nucleation" goes to the dendritic growth paper.

I noted above. Maybe mark it in your review. It would be nice if there were better review mechanisms on github for notebooks. The PR renders the notebook and reviewer would mark directly at the side of the notebook.

**Comment by wd15** [comment]
https://www.reviewnb.com/

**Comment by wd15** [comment]
I'll try and get that setup or look into how to use it. It's on my list of things.

**Comment by wd15** [comment]
@tkphd, can you see this? https://app.reviewnb.com/wd15/pfhub/blob/issue1208-bm8/benchmarks%2Fbenchmark8.ipynb

I have no idea if you can.

**Comment by tkphd** [comment]
Yep! I can see it, and got notified. Cool!

**Comment by wd15** [comment]
> Yep! I can see it, and got notified. Cool!

It's a vast improvement. Opens reviews up to more people.

**Comment by wd15** [comment]
> Yep! I can see it, and got notified. Cool!

I have no idea who has permissions to comment on that notebook.

**Comment by wd15** [comment]
@wuwenkun, can you see this and comment to test it?  https://app.reviewnb.com/wd15/pfhub/blob/issue1208-bm8/benchmarks%2Fbenchmark8.ipynb

**Comment by wuwenkun** [comment]
> @wuwenkun, can you see this and comment to test it? https://app.reviewnb.com/wd15/pfhub/blob/issue1208-bm8/benchmarks%2Fbenchmark8.ipynb

Hi Daniel, I have added my comments to the review notebook. Could you see my comments there?

**Comment by wd15** [comment]
> 
> Hi Daniel, I have added my comments to the review notebook. Could you see my comments there?

Yes, all good. Thanks!

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1230.surge.sh) is ready for review.

**Comment by tkphd** [comment]
Very minor changes requested on reviewnb. Looks pretty good!

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1230.surge.sh) is ready for review.

**Comment by wd15** [comment]
@tkphd: made modifications suggested.

Note that Reviewnb is now posting a link into this PR to their version of the PR and allowing comments in the version of the notebook rendered on their PR site, which is really nice. Reviewnb is getting better.

**Comment by tkphd** [comment]
Yeah! They were very responsive to a spellcheck issue I opened, looks like an active project. Very cool.

**Review by tkphd — APPROVED** [review]
Looks good to me!
Suggestion for @wuwenkun: if you create an arXiv record for the preprint, we can link to that until it clears peer review & publication.

**Comment by wd15** [comment]
> Looks good to me!
> Suggestion for @wuwenkun: if you create an arXiv record for the preprint, we can link to that until it clears peer review & publication.

[It's already out](https://www.sciencedirect.com/science/article/abs/pii/S0927025621000963?via%3Dihub). I fixed the link to it in the notebook.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1230.surge.sh) is ready for review.

**Pull request merged**
