### PR TITLE
feat(mms): update BM7 with auto-generated source term

### PR DESCRIPTION
**Pull request by tkphd**
**Update Benchmark 7 with auto-generated source term**

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: https://random-cat-1090.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1090)

### CODE REVIEW

**Comment by tkphd** [comment]
Not sure where the glitch was, but these CAS-derived expressions agree exactly with @stvdwtt's source term and produce a valid result.

**Comment by wd15** [comment]
Added a PR into this for the .ipynb.raw.html file which was missing otherwise LGTM

**Comment by wd15** [comment]
@tkphd, can I merge this?

**Comment by tkphd** [comment]
Yes, please.

**Pull request merged**
