### PR TITLE
upload: fenics_1a

### PR DESCRIPTION
**Pull request by wd15**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

| Field     | Content                                                                                                                                                                                                                                                                                                         |
| --------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| metadata  | [object Object]                                                                                                                                                                                                                                                                                                 |
| benchmark | [object Object]                                                                                                                                                                                                                                                                                                 |
| data      | [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] |
| date      | 1575309655                                                                                                                                                                                                                                                                                                      |

<!-- Reviewable:start -->
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/usnistgov/pfhub/1113)
<!-- Reviewable:end -->

### CODE REVIEW

**Comment by wd15** [comment]
@tkphd, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-1113.surge.sh/simulations/display/?sim=fenics_1a

and

 - https://random-cat-1113.surge.sh/simulations/1a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1113.surge.sh/simulations/upload_form/?sim=fenics_1a).

**Comment by tkphd** [comment]
@IvanYashchuk, this result took substantially longer to run than did yours. If your code is available someplace, can you post a link for comparison? Otherwise, would you mind looking at the repository for this upload and let me know if something is obviously wrong?

https://github.com/tkphd/FEniCS-spinodal-decomposition-benchmark

Thanks!

**Comment by wd15** [comment]
@tkphd, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-1113.surge.sh/simulations/display/?sim=fenics_1a

and

 - https://random-cat-1113.surge.sh/simulations/1a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1113.surge.sh/simulations/upload_form/?sim=fenics_1a).

**Comment by wd15** [comment]
@tkphd, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-1113.surge.sh/simulations/display/?sim=fenics_1a

and

 - https://random-cat-1113.surge.sh/simulations/1a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1113.surge.sh/simulations/upload_form/?sim=fenics_1a).

**Comment by IvanYashchuk** [comment]
@tkphd, your implementation looks alright to me. The main difference in speed comes from not using the static time step in my case. Also, I don't use DOLFIN's Newton Solver but PETSc's SNES, but that shouldn't matter. And I used more CPU cores, 24.
I remember I posted the link in PR for my submission, but it's gone now for some reason.
Here it is: https://gist.github.com/IvanYashchuk/f01772a439b1008710c3aea045ac37a9

**Comment by wd15** [comment]
@tkphd, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-1113.surge.sh/simulations/display/?sim=fenics_1a

and

 - https://random-cat-1113.surge.sh/simulations/1a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1113.surge.sh/simulations/upload_form/?sim=fenics_1a).

**Comment by wd15** [comment]
@tkphd, it works now, it is still very slow though. Shall I merge?

**Comment by tkphd** [comment]
The free energy curve is offset wrt the bulk of submissions, let me double-check some parameters.

**Comment by wd15** [comment]
@tkphd, is this still active?

**Comment by tkphd** [comment]
No.

**Pull request closed without merging**
