### PR TITLE
Set the benchmark version using benchmarks.yaml

### PR DESCRIPTION
**Pull request by wd15**
Address #656

Previously the benchmark version was hardwired at 1 on upload. That
now changes to the latest revision in benchmarks.yaml depending on
which benchmark ID is set.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-964.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/964)

### CODE REVIEW

**Comment by tkphd** [comment]
For Benchmark 7, this still sets the upload's version to 1, when it should be 0.

**Comment by wd15** [comment]
@tkphd, it changed it to 0 for me??? Can you try again

**Comment by wd15** [comment]
@tkphd review #970 first as this version no longer works until I merge that change into this pull request

**Comment by tkphd** [comment]
Weird. It works now.

**Pull request merged**
