### PR TITLE
upload: memphis_7b

### PR DESCRIPTION
**Pull request by wd15**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

upload: memphis_7b
benchmark_id: 7b.0
github_id: rdingre

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1169)

### CODE REVIEW

**Comment by pfhub** [comment]
@rdingre, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1169.surge.sh/simulations/display/?sim=memphis_7b

and

 - https://random-cat-1169.surge.sh/simulations/7b.0

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1169.surge.sh/simulations/upload_form/?sim=memphis_7b).

**Comment by rdingre** [comment]
Please approved.

**Comment by wd15** [comment]
@rdingre, it turns out that the current [view of the website for 7b](https://pages.nist.gov/pfhub/simulations/7b.0/) is in fact broken. The view should [look like this](https://random-cat-1173.surge.sh/simulations/7b.0/). Sorry that things weren't clearer, but a lot of this is a work in progress. 

I've also added [submission guidelines for BM7](https://random-cat-1173.surge.sh/benchmarks/benchmark7.ipynb/#Submission-Guidelines) to make the upload process clearer. 

These changes are currently in a PR awaiting approval from my coauthors. I would suggest waiting until PR #1173 is merged and then resubmitting data for 7b and 7c.  You will be the first upload for 7c, which is cool.

Once you've responded in the affirmative then I'll close this PR (and #1170) and await your follow up. I'll let you know when #1173 is merged.

**Comment by rdingre** [comment]
@wd15 Thanks Daniel. I totally understand. Looks like some of our results for BM3 and BM7 are no longer available on the benchmark website. I am assuming this is related to the above.

**Comment by wd15** [comment]
> @wd15 Thanks Daniel. I totally understand. Looks like some of our results for BM3 and BM7 are no longer available on the benchmark website. I am assuming this is related to the above.

@rdingre:

So, your upload for BM7.a (`memphis_7a`) is merged, but I forgot to repush the website again. It's up now though, https://pages.nist.gov/pfhub/simulations/7a.0/. The data can be very slow to load, which is something else that I'm working on fixing.

The upload for BM3 had not been merged yet, but still has an open PR, #1167. That is mostly ok, it's just the ordering for the dendrite contour plot that is a [little messed up](https://random-cat-1167.surge.sh/simulations/3a.1/). I'm going to try and make the frontend reorder the points then I'll merge that. Nothing for you to do on that right now. It should be able to handle unordered points. 

Note that we have temporary websites that pop up for each PR, which have domain names like https://random-cat-xxxx.surge.sh so that we can check things before pushing to the main site at pages.nist.gov.

**Comment by wd15** [comment]
@rdingre, I've fixed [BM7.b](https://pages.nist.gov/pfhub/simulations/7b.0/) on the website. I've also updated the [submission guidelines](https://pages.nist.gov/pfhub/benchmarks/benchmark7.ipynb/#Parts-(b)-and-(c)-Guidelines). Essentially, the upload requires you to evaluate a cost function versus error and wall time, respectively. This is different from the data required for [BM7.a](https://pages.nist.gov/pfhub/benchmarks/benchmark7.ipynb/#Part-(a)-Guidelines).

Anyway your [current data upload](https://raw.githubusercontent.com/memphis-snl/memphis/master/benchmark/BM_007/7b_spatial.csv) doesn't have the [correct fields](https://pages.nist.gov/pfhub/benchmarks/benchmark7.ipynb/#Part-(a)-Guidelines). Can you resubmit 7b, and 7c? Thanks

**Comment by wd15** [comment]
@rdingre, closing this, see [comment above](https://github.com/usnistgov/pfhub/pull/1169#issuecomment-587583015).

**Pull request closed without merging**
