### PR TITLE
Fix the tooltips on the upload form

### PR DESCRIPTION
**Pull request by wd15**
Address #385

Fixes all the tool tips by using icons outside of the input elements. Improve tool tip text as well.

To review go to http://random-cat-683.surge.sh/simulations/upload_form and test the tool tips and ensure they make sense.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-683.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/683)

### CODE REVIEW

**Comment by tkphd** [comment]
Reviewed 80 of 80 files at r1.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[_data/simulations/example/schema.yaml, line 103 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39jljgzFKxlEz_jWNA:-L39jljgzFKxlEz_jWNB:b-7df4d6) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_data/simulations/example/schema.yaml#L103)):*
> ```YAML
>             type: str
>             required: True
>             enum: ["serial", "multiprocessing", "threaded", "distributed"]
> ```

I think "multiprocessing" was intended to cover accelerator cards, but "Massively parallel" (or just "massive" here) is a more recognizable notation. Xeon Phi (and kin) could be considered either "massive" or "threaded", but "multiprocessing" is confusing. Sorry.

---

*[_data/simulations/example_minimal/meta.yaml, line 29 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39kDxr1fHpr4kfsNOI:-L39kDxr1fHpr4kfsNOJ:b7wnb3q) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_data/simulations/example_minimal/meta.yaml#L29)):*
> ```YAML
>     name: fipy
>     container_url: ''
>     repo:
> ```

Change "repo" to "software" if that keyword is available?

---

*[_includes/data_input.html, line 15 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39XsXaaIbAfT0Nx5ve:-L39XsXbS-aOuptaoYWd:b71uz1x) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/data_input.html#L15)):*
Provide examples, and error-throwing rules if applicable.
> Name to be displayed in graphs and summary tables, <i>e.g.</i> "fipy_1a_pysparse", using between 2 and 16 alphanumeric characters and _ (required)

---

*[_includes/data_input.html, line 57 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39ZJTfJA_WM8E_RZ_X:-L39ZJTfJA_WM8E_RZ_Y:bim2pxp) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/data_input.html#L57)):*
Explanation, not justification:
> Summary of this data contribution, highlighting important differences from existing results (required)

---

*[_includes/data_input.html, line 86 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39ZlO5lm0YM1iX7pRZ:-L39ZlO5lm0YM1iX7pR_:b-xcsc9o) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/data_input.html#L86)):*
> Heading name used for the column containing {{ this.[0] }}-axis values, <i>e.g.</i> "Time" or "Free-Energy" (required for line or contour plot data)

---

*[_includes/form_author.html, line 8 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39_Kz7MuWFX-8fU6_E:-L39_Kz7MuWFX-8fU6_F:b-spqnnu) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_author.html#L8)):*
"First" and "Last" are culturally subjective. Prefer "Given" and "Sur"-name.
> Primary author's given name (required)

---

*[_includes/form_author.html, line 31 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39_azozeiSVKnfpf0W:-L39_azozeiSVKnfpf0X:b-k1enx1) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_author.html#L31)):*
> Primary author's surname (required)

---

*[_includes/form_efficiency.html, line 28 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39_rxzjKjYytWVO1Q4:-L39_ry-zy82fuEZeb5u:b-foshpk) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_efficiency.html#L28)):*
> ```HTML
>     <a class="tooltipped prefix"
>        data-position="bottom"
>        data-tooltip="The execution end time (not wall clock time) in seconds for this result (required)">
> ```

Consider substituting "simulation" for "execution". Will the site properly handle benchmarks executed in << 1 second?

---

*[_includes/form_hardware.html, line 6 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39eeunH85j_U6LIN41:-L39eeunH85j_U6LIN42:b-fna6m0) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L6)):*
> ```HTML
>   </h5>
>   <div class="input-field col s12 m4 l4 xl3 big-buffer">
>     <select id="cpu_architecture" name="fields[metadata][hardware][cpu_architecture]" type="text">
> ```

Is there a way to make the menu default to `x86_64`?

---

*[_includes/form_hardware.html, line 24 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39evdvj-rPClvtDYzy:-L39evdvj-rPClvtDYzz:bx0cw5a) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L24)):*
> Distributed (<i>e.g.</i> MPI)

---

*[_includes/form_hardware.html, line 25 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39exkPHnuHiG8ioA3V:-L39exkQwiSfbhZLF6Jt:b5mq0i5) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L25)):*
> Threaded (<i>e.g.</i> OpenMP)

---

*[_includes/form_hardware.html, line 26 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39fJ2h6iCSzHGL7eOK:-L39fJ2h6iCSzHGL7eOL:b-ivttee) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L26)):*
> Massively (<i>e.g.</i> CUDA, OpenCL)

---

*[_includes/form_hardware.html, line 28 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39gP--_tz4gZDbhzD9:-L39gP--_tz4gZDbhzDA:bz0tgdr) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L28)):*
Consider adding
> Hybrid (<i>e.g.</i> MPI+OpenMP or OpenMP+CUDA)

---

*[_includes/form_hardware.html, line 42 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39g4W2-HuMplkn4IP4:-L39g4W2-HuMplkn4IP5:b-52d0c4) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L42)):*
Nobody's going to measure that properly.
> Peak Clock Rate (GHz)

---

*[_includes/form_implementation.html, line 44 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39gu0GgJC9sXxy5WN8:-L39gu0GgJC9sXxy5WN9:b-khlf7h) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_implementation.html#L44)):*
> The specific commit identifier (SHA hash) for the code used to run the simulation (required)

---

*[_includes/form_implementation.html, line 62 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39hWsJt6ToTwdDpgFl:-L39hWsJt6ToTwdDpgFm:b-kgwmz8) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_implementation.html#L62)):*
> Link to a container (<i>e.g.</i> Dockerfile) to reproduce this result (optional)

---

*[_includes/form_overview.html, line 1 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39i1zT60CymdZXDJqi:-L39i1zT60CymdZXDJqj:by2zkjb) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_overview.html#L1)):*
> ```HTML
> <div class="row small-buffer top-bar-thin">
> ```

See comments on `form_uploads.html`

---

*[_includes/media_input.html, line 14 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39iI_iXdOvTRFLbSyp:-L39iC9NyrVzLfMARE6m:boe8fl2) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/media_input.html#L14)):*
> Name for this media data using alphanumeric characters, `.`,  and `_`, at least 2 characters long (required)

---

*[_includes/media_input.html, line 55 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39iY-707Q-lTWYeq3c:-L39iY-707Q-lTWYeq3d:b-6rubq6) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/media_input.html#L55)):*
Need not be concise.
> Summary or "caption" of media contribution, highlighting relevant details (required)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/683)*

**Comment by tkphd** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/683)*

**Comment by wd15** [comment]
Review status: 65 of 80 files reviewed at latest revision, 19 unresolved discussions.

---

*[_data/simulations/example/schema.yaml, line 103 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39jljgzFKxlEz_jWNA:-L3FCgO3augGSd2DscEU:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_data/simulations/example/schema.yaml#L103)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

I think "multiprocessing" was intended to cover accelerator cards, but "Massively parallel" (or just "massive" here) is a more recognizable notation. Xeon Phi (and kin) could be considered either "massive" or "threaded", but "multiprocessing" is confusing. Sorry.
</blockquote></details>

Done.

---

*[_data/simulations/example_minimal/meta.yaml, line 29 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39kDxr1fHpr4kfsNOI:-L3FDKQ2MsARvIDyJY1c:b8j1okv) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_data/simulations/example_minimal/meta.yaml#L29)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Change "repo" to "software" if that keyword is available?
</blockquote></details>

What? It's the link to the repository and the commit ID for the implementation. Software is a not very well defined term. The repository might not be the software, but a particular implementation of the software. We removed the term "software" altogether in an early revision.

---

*[_includes/data_input.html, line 15 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39XsXaaIbAfT0Nx5ve:-L3FEX8cLYCbZUrwMZHm:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/data_input.html#L15)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Provide examples, and error-throwing rules if applicable.
> Name to be displayed in graphs and summary tables, <i>e.g.</i> "fipy_1a_pysparse", using between 2 and 16 alphanumeric characters and _ (required)
</blockquote></details>

Done.

---

*[_includes/data_input.html, line 57 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39ZJTfJA_WM8E_RZ_X:-L3FEjKwleLXRKU6ZCRs:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/data_input.html#L57)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Explanation, not justification:
> Summary of this data contribution, highlighting important differences from existing results (required)
</blockquote></details>

Done.

---

*[_includes/data_input.html, line 86 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39ZlO5lm0YM1iX7pRZ:-L3FFNZ9jDsGATBt0wLN:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/data_input.html#L86)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> Heading name used for the column containing {{ this.[0] }}-axis values, <i>e.g.</i> "Time" or "Free-Energy" (required for line or contour plot data)
</blockquote></details>

Done.

---

*[_includes/form_author.html, line 8 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39_Kz7MuWFX-8fU6_E:-L3FF_A90iED9dPD-g9t:bb6un1j) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_author.html#L8)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

"First" and "Last" are culturally subjective. Prefer "Given" and "Sur"-name.
> Primary author's given name (required)
</blockquote></details>

Done

---

*[_includes/form_author.html, line 31 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39_azozeiSVKnfpf0W:-L3FIXVb9DhGSTqzk4fT:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_author.html#L31)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> Primary author's surname (required)
</blockquote></details>

Done.

---

*[_includes/form_efficiency.html, line 28 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39_rxzjKjYytWVO1Q4:-L3FGc11NrsM01jHwUbA:b-51oq0t) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_efficiency.html#L28)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Consider substituting "simulation" for "execution". Will the site properly handle benchmarks executed in << 1 second?
</blockquote></details>

Done. It's displayed as loglog plot right now, so yes.

---

*[_includes/form_hardware.html, line 6 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39eeunH85j_U6LIN41:-L3FGrsfhv0rSUbP4Jrp:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L6)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Is there a way to make the menu default to `x86_64`?
</blockquote></details>

Done.

---

*[_includes/form_hardware.html, line 24 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39evdvj-rPClvtDYzy:-L3FJn1wcIV7-3lhRKFX:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L24)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> Distributed (<i>e.g.</i> MPI)
</blockquote></details>

Done.

---

*[_includes/form_hardware.html, line 25 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39exkPHnuHiG8ioA3V:-L3FJnYH4rAte65a0wlg:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L25)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> Threaded (<i>e.g.</i> OpenMP)
</blockquote></details>

Done.

---

*[_includes/form_hardware.html, line 26 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39fJ2h6iCSzHGL7eOK:-L3FRMRLBFPX278EZZ5a:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L26)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> Massively (<i>e.g.</i> CUDA, OpenCL)
</blockquote></details>

Done.

---

*[_includes/form_hardware.html, line 28 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39gP--_tz4gZDbhzD9:-L3FJu0DeyrM-UDSlwbZ:b-2nh3hy) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L28)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Consider adding
> Hybrid (<i>e.g.</i> MPI+OpenMP or OpenMP+CUDA)
</blockquote></details>

Not doing "Hybrid" - it's too complicated - maybe have checkboxes instead and change the schema so that it has true false for each one, see https://github.com/usnistgov/pfhub/issues/696

---

*[_includes/form_hardware.html, line 42 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39g4W2-HuMplkn4IP4:-L3FKB9sYVgmMfAtE3_R:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L42)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Nobody's going to measure that properly.
> Peak Clock Rate (GHz)
</blockquote></details>

Done.

---

*[_includes/form_implementation.html, line 44 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39gu0GgJC9sXxy5WN8:-L3FLx9Z6ZzGTHgFfGfE:bb7f2mf) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_implementation.html#L44)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> The specific commit identifier (SHA hash) for the code used to run the simulation (required)
</blockquote></details>

done

---

*[_includes/form_implementation.html, line 62 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39hWsJt6ToTwdDpgFl:-L3FT4l-Uy5I7KBalcmP:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_implementation.html#L62)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> Link to a container (<i>e.g.</i> Dockerfile) to reproduce this result (optional)
</blockquote></details>

Done.

---

*[_includes/media_input.html, line 14 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39iI_iXdOvTRFLbSyp:-L3FUEkLvvw-1OGQPKR4:bvzxtcr) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/media_input.html#L14)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> Name for this media data using alphanumeric characters, `.`,  and `_`, at least 2 characters long (required)
</blockquote></details>

I don't want dots in there

---

*[_includes/media_input.html, line 55 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39iY-707Q-lTWYeq3c:-L3FU9hQnR5_-YzYRaA1:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/media_input.html#L55)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Need not be concise.
> Summary or "caption" of media contribution, highlighting relevant details (required)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/683)*

**Comment by tkphd** [comment]
Reviewed 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[_data/simulations/example_minimal/meta.yaml, line 29 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39kDxr1fHpr4kfsNOI:-L3FWl8qxng8Jkf-wIzy:bv56fo0) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_data/simulations/example_minimal/meta.yaml#L29)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

What? It's the link to the repository and the commit ID for the implementation. Software is a not very well defined term. The repository might not be the software, but a particular implementation of the software. We removed the term "software" altogether in an early revision.
</blockquote></details>

OK, makes sense.

---

*[_data/simulations/inl_moose_6a/meta.yaml, line 43 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L3FWxXfBV-BpHlnc0pC:-L3FWxXfBV-BpHlnc0pD:bt4t7w7) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_data/simulations/inl_moose_6a/meta.yaml#L43)):*
> ```YAML
>     cpu_architecture: x86_64
>     nodes: '1'
>     parallel_model: multiprocessing
> ```

Since it was done on 1 node, this is probably "threaded".

---

*[_data/simulations/inl_moose_6b/meta.yaml, line 43 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L3FX1waIKKadSKYWZRL:-L3FX1waIKKadSKYWZRM:bt4t7w7) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_data/simulations/inl_moose_6b/meta.yaml#L43)):*
> ```YAML
>     cpu_architecture: x86_64
>     nodes: '1'
>     parallel_model: multiprocessing
> ```

Since it was done on 1 node, this is probably "threaded".

---

*[_includes/form_hardware.html, line 28 at r1](https://reviewable.io:443/reviews/usnistgov/pfhub/683#-L39gP--_tz4gZDbhzD9:-L3FXJtkyfBCndI2QP-s:b-rav7ft) ([raw file](https://github.com/usnistgov/pfhub/blob/d9d75cf1b38145234d3d7ec0b3a521aa9ede3685/_includes/form_hardware.html#L28)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Not doing "Hybrid" - it's too complicated - maybe have checkboxes instead and change the schema so that it has true false for each one, see https://github.com/usnistgov/pfhub/issues/696
</blockquote></details>

Good solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/683)*

**Pull request merged**
