### PR TITLE
PFHub Upload: inl_moose_3a_faster

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

| Field     | Content                                                                                         |
| --------- | ----------------------------------------------------------------------------------------------- |
| metadata  | [object Object]                                                                                 |
| benchmark | [object Object]                                                                                 |
| data      | [object Object],[object Object],[object Object],[object Object],[object Object],[object Object] |
| date      | 1554243280                                                                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/957)

### CODE REVIEW

**Comment by wd15** [comment]
@dschwen, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-957.surge.sh/simulations/display/?sim=inl_moose_3a_faster

and

 - https://random-cat-957.surge.sh/simulations/3a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-957.surge.sh/simulations/upload_form/?sim=inl_moose_3a_faster).

**Comment by dschwen** [comment]
@wd15, this looks good. I double checked the memory usage and it is correct. I suspect some of the other MOOSE runs for that benchmark are bogus.

**Comment by wd15** [comment]
@dschwen, maybe we need some sort of text on the upload page about best practices regarding measuring memory usage.

**Comment by dschwen** [comment]
Or maybe we need a mechanism to deprecate old / wrong / clumsy results?

**Comment by wd15** [comment]
@dschwen, I have to implement #500

**Pull request merged**
