### PR TITLE
upload: memphis_1a

### PR DESCRIPTION
**Pull request by wd15**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

upload: memphis_1a
benchmark_id: 1a.1
github_id: rdingre

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1161)

### CODE REVIEW

**Comment by pfhub** [comment]
@rdingre, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1161.surge.sh/simulations/display/?sim=memphis_1a

and

 - https://random-cat-1161.surge.sh/simulations/1a.1

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1161.surge.sh/simulations/upload_form/?sim=memphis_1a).

**Comment by tkphd** [comment]
Hi @rdingre,

There seems to be a small oversight in this upload. The repository provided under "Implementation" contains the CSV *output* of the simulations, but no input files or source code are available. Can you post these implementation details? Thanks!

Applies also to #1162, #1163, #1164, #1165, #1166.

**Comment by wd15** [comment]
@rdingre: It looks like all you are missing is the [name of the code](https://github.com/usnistgov/pfhub/pull/1161/files#diff-213bf422304f85db02cb6a45d2d33b98R10). You've put your own name instead. Now worries though as the URL for the code seems to be there. I'm assuming that you want to call your code "memphis" for the purposes of PFHub. So, I can fix all of these to save you the bother of going through the upload process again.

> Hi @rdingre,
> 
> There seems to be a small oversight in this upload. The repository provided under "Implementation" contains the CSV _output_ of the simulations, but no input files or source code are available. Can you post these implementation details? Thanks!
> 
> Applies also to #1162, #1163, #1164, #1165, #1166.

**Comment by wd15** [comment]
@rdingre: closing this in favor or #1165

**Pull request closed without merging**
