### PR TITLE
chore: stop stalebot closing issues

### PR DESCRIPTION
**Pull request by wd15**
- Stop Stalebot closing issues
 - Update Surge token
 - Stop checking Twitter links as htmlproofer not working with Twitter links (don't know why)
 
**Remember to tear down the live site when merging or closing this
pull request.**

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1232)

### CODE REVIEW

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1232.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1232.surge.sh) is ready for review.

**Comment by tkphd** [comment]
It looks like StaleBot will only make a comment and apply the "wontfix" label after 365 days. Is this useful to you, @wd15? What if we delete `stale.yml` wholesale? Or, set the auto-close timeout to something longer than 365 days, but shorter than the lifetime of the universe? We probably adopted StaleBot for a reason. Worth reassessing.

**Comment by wd15** [comment]
@tkphd, removed statebot. It has no utility for a project that currently isn't getting enough attention.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1232.surge.sh) is ready for review.

**Review by tkphd — APPROVED** [review]
LGTM

**Pull request merged**
