### PR TITLE
upload: moose_2a_guan

### PR DESCRIPTION
**Pull request by wd15**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

upload: moose_2a_guan
benchmark_id: 2a.1
github_id: xiaoyuguan

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1221)

### CODE REVIEW

**Comment by pfhub** [comment]
@xiaoyuguan, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1221.surge.sh/simulations/display/?sim=moose_2a_guan

and

 - https://random-cat-1221.surge.sh/simulations/2a.1

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1221.surge.sh/simulations/upload_form/?sim=moose_2a_guan).

**Comment by xiaoyuguan** [comment]
Confirm. @pfhub

**Comment by xiaoyuguan** [comment]
Hi, @pfhub I'm new user of github and FEM, and this is my first time uploading the benchmark problem results. After I upload the results for the problem 1&2, all of them show 2 failing checks about the travis CI build failed. I checked the details of the error but I have no idea what's that means:

The command "nix-shell --command " pylint _data/*.py && flake8 _data/*.py && LC_ALL=en_US.UTF-8 black --check _data/*.py && LC_ALL=en_US.UTF-8 make simulations && find . -name '*.ipynb' -type f -not -path '*/.ipynb_checkpoints/*' -exec touch {} \; && make notebooks && rm -rf ./_site && jekyll build -d ./_site/pfhub && htmlproofer --check-html --only-4xx --allow-hash-href --empty-alt-ignore --checks-to-ignore ImageCheck --file-ignore ./_site/pfhub/node_modules ./_site && py.test --ignore=hackathons/hackathon1 --ignore=benchmarks --ignore=_data --nbval --sanitize-with sanitize.cfg && coffeelint _includes/coffee/ && mocha _site/pfhub/js/test.js ";" exited with 2.

Would anyone check for me and suggest how to deal with it?

**Comment by wd15** [comment]
@xiaoyuguan, Thanks for all the uploads. I'm going to work on them one at at time, [starting with this one](https://github.com/usnistgov/pfhub/pull/1214). I'll let you know in that PR when things are ready and you should look over it again. Thanks.

**Comment by wd15** [comment]
@xiaoyuguan - closing this PR as I think this is a duplicate of #1214

**Pull request closed without merging**
