### PR TITLE
Implementation of Surge teardown after PR closed

### PR DESCRIPTION
**Pull request by wd15**
- [surge-teardown.yml](https://github.com/usnistgov/pfhub/blob/master/.github/workflows/surge-teardown.yml) had to be committed to master to test
 - Example of it's use here #1472, see the comment demonstrating the teardown on closing the PR
  
**Remember to tear down the live site when merging or closing this
pull request.**

### CODE REVIEW

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1473.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1473.surge.sh

**Review by tkphd — APPROVED** [review]
This is awesome!

**Comment by pfhub** [comment]
Successful teardown of random-cat-1473.surge.sh

**Pull request merged**
