### PR TITLE
PFHub Upload: moose_2a_xueyang94

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

| Field     | Content                                         |
| --------- | ----------------------------------------------- |
| metadata  | [object Object]                                 |
| benchmark | [object Object]                                 |
| data      | [object Object],[object Object],[object Object] |
| date      | 1549567385                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/931)

### CODE REVIEW

**Comment by wd15** [comment]
@xueyang94, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-931.surge.sh/simulations/display/?sim=moose_2a_xueyang94_update

and

 - https://random-cat-931.surge.sh/simulations/2a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-931.surge.sh/simulations/upload_form/?sim=moose_2a_xueyang94_update).

**Comment by wd15** [comment]
@xueyang94, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-931.surge.sh/simulations/display/?sim=moose_2a_xueyang94

and

 - https://random-cat-931.surge.sh/simulations/2a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-931.surge.sh/simulations/upload_form/?sim=moose_2a_xueyang94).

**Comment by wd15** [comment]
@xueyang94, please check this over now and see that you're happy with it. I fixed a few things.

**Comment by xueyang94** [comment]
@wd15 Thanks but I will run the simulation for a longer time to see if I can bring the free energy lower, and upload again when I get a better result. The current plot doesn't compare very well with others' results.

**Comment by dschwen** [comment]
@xueyang94 you MOOSE simulation already runs between two and three orders of magnitude slower than the existing MOOSE benchmarks that have already been uploaded. I am seriously wondering what the point of this upload is.

**Comment by wd15** [comment]
@xueyang94, so, would you like me to merge this or would you like me to wait? You can always merge and update later.

**Comment by xueyang94** [comment]
@wd15 Yes please merge this and I will update later.

**Pull request merged**
