### PR TITLE
Apply DRY principle to workflows

### PR DESCRIPTION
**Pull request by wd15**
Combine workflows to avoid duplication. Some of this was done directly on master for testing purposes, see [surge.yml](https://github.com/usnistgov/pfhub/blob/master/.github/workflows/surge.yml).

A comment will appear below when the live site is built. This normally
takes a few minutes.

### CODE REVIEW

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1475.surge.sh

**Review by tkphd — APPROVED** [review]
PR deduplicates common code in two workflows. Nice, and LGTM!

**Comment by pfhub** [comment]
Successful teardown of random-cat-1475.surge.sh

**Pull request merged**
