### PR TITLE
feat: implement direct file upload using box

### PR DESCRIPTION
**Pull request by wd15**
Address #1012

Implement direct file upload via Box. The first commit is to develop the app which is currently running on app engine. The second commit develops the upload form.

To review, go to the Surge link and try to upload some data. Check that the URLs generated from the meta.yaml are correct for your data. Also, evaluate how the form looks and if we need to make it clearer. Should we include more data in the meta.yaml about the link (box ID, or other data about the file to make accessible). Note that we shouldn't get to hung up on the Box data at this stage as eventually the Box data will only be temporary (see below).

## Next Step

The Box files will be temporary as the data with eventually be uploaded to MDF, #900, when the PR is merged. This is the next step. The files can then be purged from Box.

The long term vision is to have an app that can run Globus and upload big files directly to MDF and then we don't need Box at all, but this is a much longer term goal and I'm unsure currently if this will ever be possible. We probably wouldn't be able to run such an app from app engine or Heroku. 

## Other Issues

 - We probably should have some sore of authentication to stop spam data. Plan is to implement Github authentication only for the upload form #885 
 - Also, recaptcha #359 
 - I currently can't view the Box data, needs fixing. It's being stored at Chicago or ANL, #1137 
 - Both apps ("data" and "box") need to be combined into a single app and run from Heroku, which is easier to deal with than app engine #1136 
 - [edit] tiny URL is being used to minimize the Box URL - removing this now

**Remember to tear down the live site when merging or closing this
pull request.**

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1135)

### CODE REVIEW

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by wd15** [comment]
@guyer I added you on the off chance that you'd like to review. Just take your name off if you don't have time.

**Comment by tkphd** [comment]
@guyer should definitely review, as the most vocal critic of our upload process.

**Comment by tkphd** [comment]
I do not like that `meta.yml` stores a tinyurl instead of the raw Box link. Is there a technical reason for this? Is that just what Box hands back to you?

**Comment by wd15** [comment]
> I do not like that `meta.yml` stores a tinyurl instead of the raw Box link. Is there a technical reason for this? Is that just what Box hands back to you?

That is my doing. The URL from Box is absolutely massive. An alternative is to store the Box file ID. Also, we could just store the Box URL and don't worry about it. I guess the YAML file becomes less readable with a colossal URL in it. What do you think?

**Comment by tkphd** [comment]
I'm in favor of transparency as to where the data actually resides, so, massive URL is my preference. The tinyURL may be easier on humans, but, these files are not really for us. If the URL can be reduced to an unique Box file ID, that might also work, but at the cost of generality.

**Comment by wd15** [comment]
>
> If I were greedy, I'd wish for popup menus or something to choose the column names from the headers that are in the file

I've included this as part of #881, I think it's in another issue somewhere as well.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by wd15** [comment]
@tkphd, I removed the tiny url stuff.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Comment by wd15** [comment]
@tkphd, try it again. I'm not sure why yours didn't work at the moment. I need to see a consistent failure to try and fix it and I can't get it to fail.

**Comment by tkphd** [comment]
[PEBKAC](https://en.wiktionary.org/wiki/PEBKAC) (I "fixed" the column names to nonexistent strings).

**Comment by wd15** [comment]
Ok, that doesn't explain why the link was broken regardless of the contents
of the file. The URL failed to download anything for me, which is weird.

**Comment by tkphd** [comment]
When you say it failed to download anything for you, what do you mean? Does the link do anything?

When I copy the [data URL](https://dl.boxcloud.com/d/1/b1!m0n-3VcYWHvQtNh8eTDSDV0-yZ_9vvMpOFG5R1xWPKdMK0Ye9TL9UWCoon9Vr8ic9aFdPjrqB2acT1s8VISAIJZYIB9ANNK39N4goZh5kRtx75qRRniKuV2jiPYFXrYNCJzRfomoncz1MVpXOIS2vIMLe0hFCiISGdHJnO-2BM9AsKA_c4JIqBYVQm9ksJHDmbXuWoEtMk0NYymL5qeY0LCai9b5WS7YhxnH3jWgPZYIV4C9AeggBtsp4cbYLnHkoRJXRNiA6oYBH2GdiwHUuvITY4sVgk6nkCq05a8XKDYRAmr70KQpvhcy7-lUbEAYjp9bqlbzoloqQq0hWgViY7cAlDvvUM_kU8_MyxCZJfdN_5Z0XKlPC8C4-GCTtQx_Q8pEvsWZJoEqKlZ71YWco47jCq2YmsA5Ks4lvr4LYlji9LOzQJ4bZW3BffQYjBnVScAscKzUiALevKxo4IXOLONqbnHPXpQS-1JRKqvx3kSuZqhWZcATqic7p0BlxNLJwNPv9Ia1BXOtoKqzs-Bto_aKCHYQi9R2Rwgd0mVrUoay8aDkJPNLZ7wD0U0uAA36r2HggmjDBRsJEjZ8MtpHmhyUPZLhVuabRxnnWjQ-HCPC4LBC3uWeJ_J_uIsgUPn4QzMe-U7UvCvq2l5iOHRYxEUSz_99ugsEg0DA028966JQRfCp6SJqJrKrmsh2zNoybKarDruT6dRmrm8__Hh_esDH8cWis_rjBrfxLgQ1SLpl_tXLjZubyDZOZRmhYrV_Gh3hooFxCPF50wE3E0h9OcVFImZMUQFH_Q6DtkleJvCLfhRzwbCfw8oz8BCpMduKU5EHu4OudUKY4DGZqeJwekWQbSqFaxW5B6G9EZYjul6W-gDCnPuccNDN7yvZZjkiWHI29UTJgnUshBToIqh9bBwp6CUeS6zlCA8LlNL2OlrwKkgYW1F5S0eAHtLZcHzfhOM53aovxk6-Sqpj45NRs5JDk4PU2uOEn5IaxJdYAZBAdPlgHtNxYvUdElcnLBQdeJDH4zkZmCAfmK9kWTNNHmAoxKiTGentcc1-RzCaa928flbZe9iRL6abZ87IQd4iAIvtAkbwVA-osYCP5xBogdr2ItvQ7kTxZhOi6pk-_1qc76od3Qejc2yB0eWn3-GvXIH31bzRefIzOheLsFIdFB89z5UX8yp0YZ2EI28oRLUEI-h1LDkGC4pWzf_DeSzpGOQDVKmpOcX2K3FHJPvCLWRbiflFEJd-9unGtWtZHD_Oj0uVzFW9XBbOYjmDkSXS__E_eRRcm-6RP3p-cdbDA4MVBQHRTvM./download
) from #1153, the Box page says "The link you're trying to access can't be used to share files. Please ask the file owner to provide you with a shared link instead."

**Comment by tkphd** [comment]
The [data URL][box] in #1160 *does* download a copy of the file I uploaded. Appears to be functioning as intended.

[box]: https://dl.boxcloud.com/d/1/b1!_hjUKrRKcCfUqRpPYKBCemTXMZgNlckL_2GQakBSCGcoCw1Rk60y8XekGxe2sxioy2zWKSwJwNv1CCJvp7kH0OMzW5Wt-XMP5lRgrSL7Z_D6Qi1FVmBu_476zV_43WK1_v5otwuUpV7_7Z62Xm0ud1PzxR1yWv2uIdU7h7823vk-dTbI1mkeNsXwEodXvsH-8ghJ7C-S0F_inaUEVhpayUlgnDere1HcLU3ysez9Ys9Vd1O5c5743IxfM96Hi8dDc-GNv0tA3dOqEMu4H8b0NO6Cx1KMmTDQnsnf5IFn8qKE17-8xkA0Z2cmJyvtf1YD-mQ8hcCWYoCwIqh0v26JccDHT4zCW__IkMRgng671_ihMR8HL12CXcqg1I5nOPdK-ZdLdZjr7g4OFuiSv9SAxZRj_KNNurs6xkCnx48ufvowrlazTuWc3lmtuE5djG-7EOlZNR67tVxUcLL4ZQsnqXAHrNxkQmDsFQxs5FwlIPXfcCvCnbQUYyZZEiKepVsJLcXKANXjaoGs07EUkIzJhQKSvEuS1RUJdxUg3wsUbhStHLgEnE8fJrMk91sB38GLy6ZErBi9LmnEtVS7MziID8DmB3S_KRB8v2OHPkE7HZS0RvdfrMu1sNg_BhAhOzgFpFu4435cCtATRug39nII05paEjJjN8DhikZCo7-DWrPfauBjuR-SrpBcponoKMnKQ_sQzJugBZqXGfh6KEkKNhUG58UQG9rdbH4Em14ahxvNt7QT0tByPnNoXzIFoAGpjGrYf1U_-2TSDyw30phho1QYOKMWboVOLc8otJaTA2z6QltD86mcEzIaYxTQ5xtgpn0Atb6u484p7S6doLqLe_q_7JKGFSOCFtY05PeLn-a0G4mlKQ9qd7vdVxYf6wYO9SuQF5kW8PE0Shdd3SCcU546OVdwgsGdwWaJApApM_zSy3izl6t0C00k0fL3AwvGFrQ1GWc-zfPP9GUWmpsEWeoxuuzQWoc5u4dmuQzXlmb-zHIJ9Dnl8XE67vhNktEoQUHVofJaEuj_HB0ftWy8SpgQu8hBc-268inoMx7nB5U6KqkEucDdpidZoNCHDRpMfLN54_cAQKL6qgqRP4FzlSXpOgZmdSIyGlvhbsX2tCnzfwG0k7DjHLhRZkNn6yz7KcEeSsBAllLTdqlXEAXJdnwCctQJs5fRp00mGYOkgfwa5dCw97SqmF-jzS9nOrk91zAHBntZC098OMEJTya56mDMPl2aHX6Cz1XTryAnbImIG9wTBL5ZTnKqdYjBrGZydnVFCHDQhioZGqgx2vocYRhE9L3xSg../download

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1135.surge.sh) is ready for review.

**Pull request merged**
