### PR TITLE
upload: memphis_7a

### PR DESCRIPTION
**Pull request by wd15**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

upload: memphis_7a
benchmark_id: 7a.0
github_id: rdingre

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1171)

### CODE REVIEW

**Comment by pfhub** [comment]
@rdingre, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1171.surge.sh/simulations/display/?sim=memphis_7a

and

 - https://random-cat-1171.surge.sh/simulations/7a.0

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1171.surge.sh/simulations/upload_form/?sim=memphis_7a).

**Comment by rdingre** [comment]
Please approve.

**Comment by wd15** [comment]
You're getting a very good order of accuracy on this. Is it as you intended? 

I'm assuming that you intentionally left out the temporal accuracy?

I'm going to merge this anyway, but if you answer the above question it would be helpful. The result links back to the PR so can be useful follow up explaining what you're trying to do with the simulation.

**Comment by rdingre** [comment]
Hi Daniel,

Yes for now we left out the temporal results for BM 7. The spatial results looks as intended. My postdoc and I messed something up in the results so we are trying to figure this out. Same on BM 4. We have done a bunch of simulation for 4a-4d but something bugs me about the results we get so we are re-running everything to make sure we haven’t done something stupid.

Also, last week you mentioned that there is a PFHub workshop later this year. If this is something I could attend that would be good but I also don’t want to impose an invitation.

Cheers,

Remi




--
Remi Dingreville, Ph.D.
Center for Integrated Nanotechnologies
Nanostructure Physics
Sandia National Laboratories
Albuquerque, NM 87185
@            : rdingre@sandia.gov<mailto:rdingre@sandia.gov>
T              : +1 505.844.9083
Homepage: http://www.lanl.gov/expertise/profiles/view/remi-dingreville



On Feb 10, 2020, at 12:01 PM, Daniel Wheeler <notifications@github.com<mailto:notifications@github.com>> wrote:


You're getting a very good order of accuracy on this. Is it as you intended?

I'm assuming that you intentionally left out the temporal accuracy?

I'm going to merge this anyway, but if you answer the above question it would be helpful. The result links back to the PR so can be useful follow up explaining what you're trying to do with the simulation.

**Comment by wd15** [comment]
> Hi Daniel, Yes for now we left out the temporal results for BM 7. The spatial results looks as intended. My postdoc and I messed something up in the results so we are trying to figure this out. 

That's fine. I merged the results for 7a.

Regarding 7b and 7c, the website doesn't have any (or just one) results for these yet. I need to check that your upload makes sense and I may ask you to make some changes. I'm just trying to figure out if our instruction for part b and c make sense and also whether your results make sense.

https://random-cat-1170.surge.sh/benchmarks/benchmark7.ipynb/#Part-(b)

The first few uploads for a new problem always take a bit of iteration as the plots probably need some adjusting on the website.

>Same on BM 4. We have done a bunch of simulation for 4a-4d but something bugs me about the results we get so we are re-running everything to make sure we haven’t done something stupid.

Great. Looking forward to that. Again, the results that are up there right now are just placeholders and not correct (especially for b, c, and d). For now you should consult the paper, https://www.sciencedirect.com/science/article/pii/S092702561830168X?via%3Dihub to check your results rather than the website.

**Pull request merged**
