### PR TITLE
Add the spec for benchmark 7 (take 2)

### PR DESCRIPTION
**Pull request by stvdwtt**
Address #519

Here's the draft version of benchmark problem 7. This is the second attempt after @wd15 noticed that #715 had a bunch of unrelated files modified.

I tried to modify the upload instructions to be consistent with the current upload form. Is the intent that the data sets given in the upload form have a one-to-one correspondence with plots? I wasn't assuming that was the case, so I asked users to upload a four column data set. From those four columns I figured we could make several graphs. I included a note to only enter the names of three of the columns on the upload form since it currently only supports 2D and 3D data sets.

(Due to a lack of Git/GitHub skills I just checked out the notebook from the messy branch from a copy of the main pfhub master. This loses the commit history. [Obligatory xkcd reference.](https://xkcd.com/1597/))

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

*edited to fix surge URL*

[live-site]: http://random-cat-716.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/716)

### CODE REVIEW

**Comment by wd15** [comment]
@stvdwtt, I did a [pull request](https://github.com/stvdwtt/chimad-phase-field/pull/5) to fix the tests and make sure that the benchmark has links

**Comment by wd15** [comment]
On Fri, Jan 26, 2018 at 3:10 PM, Stephen DeWitt
<notifications@github.com> wrote:
>
> I tried to modify the upload instructions to be consistent with the current upload form. Is the intent that the data sets given in the upload form have a one-to-one correspondence with plots? I wasn't assuming that was the case, so I asked users to upload a four column data set. From those four columns I figured we could make several graphs. I included a note to only enter the names of three of the columns on the upload form since it currently only supports 2D and 3D data sets.

A CSV or JSON file can have as many columns as you like. Each data
section of the upload form refers to a given graph or contour plot
that will be generated on the website. However wo different data
sections can refer to the same data file. For example, I could have
one data file

````
time, free_energy, mass
```

and make plots of both time versus mass and time versus free_energy. I
would need to two data sections, but they would refer to the same
file.

-- 
Daniel Wheeler

**Comment by wd15** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[benchmarks/benchmark7.ipynb, line 165 at r2](https://reviewable.io:443/reviews/usnistgov/pfhub/716#-L4M9fJkkIyAOa-AXUxO:-L4M9fJkkIyAOa-AXUxP:bt1huzo) ([raw file](https://github.com/usnistgov/pfhub/blob/d855790390181ea61fc7cede359196c330758a91/benchmarks/benchmark7.ipynb#L165)):*
> ```
>     "* [Appendix](#Appendix)\n",
>     "    * [Computer algebra systems](#Computer-algebra-systems)\n",
>     "    * [Source equation](#Source-equation)\n",
> ```

I think that #Source-equation is a broken link, see https://travis-ci.org/usnistgov/pfhub/builds/336286603#L1562. Remember to run `make notebooks` after you update the this. That generates a new HTML version of the notebook.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/716)*

**Comment by stvdwtt** [comment]
Ah, ok. I have to fix up the upload information as well.

**Comment by stvdwtt** [comment]
@wd15 I'm not able to run `make notebooks` on my machine.

I set up a conda environment as described in [the development directions](https://pages.nist.gov/pfhub/DEVELOPMENT/#new_notebook), but when I run `make notebooks` I get:
`$ (test-environment) vega:chimad-phase-field stephendewitt$ make notebooks`
`cp -n ./template.ipynb.md benchmarks/benchmark1.ipynb.md`
`make: *** [benchmarks/benchmark1.ipynb.md] Error 1`

I'm not quite sure what to do with that. I think this is still the same error I had when we first overhauled the development page.

**Comment by wd15** [comment]
@stvdwtt, I can rerun `make notebooks` for you and do another pull request if you can't get things working.

**Comment by wd15** [comment]
On Fri, Feb 2, 2018 at 1:09 PM, Stephen DeWitt <notifications@github.com> wrote:
>
> @wd15 I'm not able to run make notebooks on my machine.
>
> I set up a conda environment as described in the development directions, but when I run make notebooks I get:
> $ (test-environment) vega:chimad-phase-field stephendewitt$ make notebooks
> cp -n ./template.ipynb.md benchmarks/benchmark1.ipynb.md
> make: *** [benchmarks/benchmark1.ipynb.md] Error 1

The error is copying a file? Can you do that at the command line? Is
that the full extent of the error message?

-- 
Daniel Wheeler

**Comment by stvdwtt** [comment]
@wd15 I think the error happens for the instruction after the file is copied. Copying the file at the command line works fine, but then if I retry `make notebooks`, I get the same error message.

Yes, unfortunately ` make: *** [benchmarks/benchmark1.ipynb.md] Error 1` is the full extent of the error message.

**Comment by wd15** [comment]
@stvdwtt: it's the `sed` command then. You can try that at the command line, but maybe just update notebook7 with the link fix I mentioned above and I'll run `make notebooks` and make another pull request.

**Comment by stvdwtt** [comment]
I verified that the broken link is fixed. I haven't gotten the `sed` command to work, so if you could make the notebooks I'd appreciate it.

**Comment by wd15** [comment]
@stvdwtt: I did a pull request into your branch. Hopefully, we'll be ready you merge it.

**Pull request merged**
