### PR TITLE
Add Slack link in navbar

### PR DESCRIPTION
**Pull request by wd15**
These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-992.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/992)

### CODE REVIEW

**Comment by tkphd** [comment]
For the un-initiated, clicking the link offers a login prompt with the message

> Don't have an account on this workspace yet?
> Contact the workspace administrator for an invitation

Is there a way to make this less exclusive at first glance?

**Comment by wd15** [comment]
@tkphd, I don't think there is a way to change the message on Slack. What about an intermediate web page explaining how to get Slack?

**Comment by tkphd** [comment]
@guyer, do you know if the unhelpful greeting message can be changed?
@wd15, maybe. It seems unnecessarily messy to have an intermediate landing page with directions for getting on Slack, when it's something "we" (the Slack cognoscenti) control.

**Comment by guyer** [comment]
@tkphd The signup options seem to be constrained to those shown. We may need to make the toolbar icon be an exlicit  "invite me to join" action.
image

**Comment by tkphd** [comment]
Switching the icon link to an "Invite Me To Join" seems like a better pathway, assuming it redirects logged-in members straight to the channel.

**Comment by wd15** [comment]
There is no way to do this. I can't check if someone is logged in to pfhub.slack.com from the client side of PFHub. I can't access pfhub.slack.com because of CORS and I can't get access to the browser cookies from another page. Also, the Slack API won't give me access to anything useful without a token which isn't a good idea to have client side.

**Pull request merged**
