### PR TITLE
Benchmark 7 notebook

### PR DESCRIPTION
**Pull request by stvdwtt**
Address #519 

Here's the draft version of benchmark problem 7.

I tried to modify the upload instructions to be consistent with the current upload form. Is the intent that the data sets given in the upload form have a one-to-one correspondence with plots? I wasn't assuming that was the case, so I asked users to upload a four column data set. From those four columns I figured we could make several graphs. I included a note to only enter the names of three of the columns on the upload form since it currently only supports 2D and 3D data sets.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

*edited to fix surge URL*

[live-site]: http://random-cat-715.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/715)

### CODE REVIEW

**Comment by wd15** [comment]
@stvdwtt, for some reason, 52 files have been touched in this pull request. My advice would be to start over with this pull request from pfhub's current master branch. Maybe sacrifice the history of your notebook and Trevor's commits.

**Comment by wd15** [comment]
Quite a few files added of the form ` hackathons/hackathon1/moose/index.ipynb.md--` with a `--` at the end.

**Comment by wd15** [comment]
Also, `_data/simulations/prismspf_2a/meta.yaml` has been added. Why don't we do any new simulations in a different pull request from the new notebook. Again, maybe try starting from pfhub/master for these as the schema has changed.

**Comment by stvdwtt** [comment]
Ok, trying a clean PR.

**Comment by wd15** [comment]
@tkphd, Any way to preserve your commits on this one and get around @stvdwtt messed up master branch? @stvdwtt could start from before your changes were merged and [cherrypick](https://git-scm.com/docs/git-cherry-pick) your commits. I'll let you guys figure it out.

**Comment by tkphd** [comment]
I can take a look at my local branch and see if I can cherry-pick on it? This is an unusual situation, should be interesting...

@stvdwtt, consider making a backup tarball of the `chimad-phase-field/.git` directory before beginning any history-modifying operation.

**Comment by stvdwtt** [comment]
I just did the brute force approach of creating a new branch and a new PR ( #716 ). Sorry @tkphd that it loses the history of your edits.

**Comment by tkphd** [comment]
I'll try to clean up the original branch that preserves history anyway; if cherry-picking can't fix it, the brute-force approach makes a good fallback to merge.

**Comment by tkphd** [comment]
... not worth the effort. Recommend merging #716 instead.

**Pull request closed without merging**
