### PR TITLE
Benchmark 1a fix and 1b solution.

### PR DESCRIPTION
**Pull request by mfrichtl**
I discovered I was not properly tracking total memory usage for my benchmark 1a solution, so I re-ran it and have updated my results. These put my efficiency more in line with other MOOSE results. Sorry for the incorrect reporting in my last PR.

I also included my solution for benchmark 1b. It includes the correct memory usage, so is hopefully good to go.

### CODE REVIEW

**Comment by pfhub** [comment]
@mfrichtl, the new version of the PFHub website is available at https://random-cat-1487.surge.sh

**Comment by wd15** [comment]
@mfrictl, thanks for the upload. I have a pull-request waiting for review that addresses some upload issues (#1482). When that's merged, then I can repair and merge any issues on this one. Thanks for your patience!

**Comment by mfrichtl** [comment]
@wd15 No problem. I'm far from a github guru, but it looks like the only failure I see in the build is related to an external html check routine. Let me know if there's anything that I need to fix on my end.

**Comment by pfhub** [comment]
@mfrichtl, the new version of the PFHub website is available at https://random-cat-1487.surge.sh

**Comment by wd15** [comment]
@mfrichtl: please take a look and check things. It looks good to me. 

1a: https://random-cat-1487.surge.sh/results/benchmark1a.1.ipynb/
1b: https://random-cat-1487.surge.sh/results/benchmark1b.1.ipynb/

**Comment by mfrichtl** [comment]
@wd15 I agree. I think it looks good. Please let me know if there's anything I can do to address the build failure issue on my side.

**Comment by guyer** [comment]
Hard to know what I'm looking at. The notebooks look fine, but the files changed are dominated by things that @mfrichtl didn't do, AFAICT.

**Pull request closed without merging**
