### PR TITLE
PFHub Upload: fenics_1a_ivan

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

| Field     | Content                                         |
| --------- | ----------------------------------------------- |
| metadata  | [object Object]                                 |
| benchmark | [object Object]                                 |
| data      | [object Object],[object Object],[object Object] |
| date      | 1541755342                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/919)

### CODE REVIEW

**Comment by wd15** [comment]
@IvanYashchuk, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-919.surge.sh/simulations/display/?sim=fenics_1a_ivan

and

 - https://random-cat-919.surge.sh/simulations/1a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-919.surge.sh/simulations/upload_form/?sim=fenics_1a_ivan).

**Comment by IvanYashchuk** [comment]
Looks fine to me.

**Comment by wd15** [comment]
@IvanYashchuk, thanks for all the uploads! Keep them coming.

**Comment by wd15** [comment]
@IvanYashchuk, could you perhaps give a link to the input files for each of the problems? Just paste it as a comment in this pull request. In the future, we're going to have a separate URL for the code and the input files.

**Comment by IvanYashchuk** [comment]
Here is the code for the first benchmark cases: https://gist.github.com/IvanYashchuk/f01772a439b1008710c3aea045ac37a9
There is `create_mesh_benchmark1.py` to generate meshes I used for cases (c), (d).
I suggest using docker/singularity. The following command should work (not tested)
```
singularity exec docker://quay.io/fenicsproject/stable:current python3 benchmark1.py
```

**Pull request merged**
