### PR TITLE
add pfhub citation to readme

### LINKED ISSUE #1036: Add easily searchable citation links to front page and README

### PR DESCRIPTION
**Pull request by wd15**
Fix #1036

A comment will appear below when the live site is built. This normally
takes a few minutes.

**Remember to tear down the live site when merging or closing this
pull request.**

### CODE REVIEW

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1423.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1423.surge.sh) is ready for review.

**Comment by pfhub** [comment]
The new [PFHub live website](https://random-cat-1423.surge.sh) is ready for review.

**Review by tkphd — APPROVED** [review]
LGTM!

**Pull request merged**
