### PR TITLE
Update BM7 to use papermill workflow

### PR DESCRIPTION
**Pull request by wd15**

### CODE REVIEW

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1505.surge.sh

**Comment by wd15** [comment]
@tkphd, ready for review, see https://random-cat-1505.surge.sh/results/benchmark7a.0.ipynb/

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1505.surge.sh

**Comment by tkphd** [comment]
Looks good!
It would be better if the color for each dataset matched between the two graphs. Is that possible?

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1505.surge.sh

**Comment by wd15** [comment]
@tkphd, this is ready for review now

**Review by tkphd — CHANGES_REQUESTED** [review]
Much better, @wd15.

* _Required:_

  * In the temporal accuracy plot,
    * Change $h$ to $k$, since the slope is against the timestep, not mesh spacing.
    * Change the order of $\mathcal{O}(k)$ and $\mathcal{O}(k^2)$ in the Temporal Accuracy plot so 
      that the first-order and second-order trendlines have the same line style in both plots.
  * Use words in the axis labels.
    * Temporal:  
      $L^2$ norm of the error, $e_{L2}$ ___vs.___ Timestep, $k = \Delta t$
    * Spatial:  
      $L^2$ norm of the error, $e_{L2}$ ___vs.___ Mesh resolution, $h = \Delta x$

* _Optional:_

  * For both accuracy plots, the grid lines are unconventional: equal spacing leads one to expect 
    linear scales, but these are log-log plots. Especially since the values are less important 
    than the slope of the trendlines, can these plots be regenerated using more standard
    log-scaled semiology? I.e., grid lines at the powers of 10 with minor ticks along the axes 
    showing log-spacing.

**Comment by tkphd** [comment]
(Implicitly, in the trendline labels, please use `$\mathcal{O}(•)$`)

**Comment by wd15** [comment]
> 
>     * _Optional:_
>       
>       * For both accuracy plots, the grid lines are unconventional: equal spacing leads one to expect
>         linear scales, but these are log-log plots. Especially since the values are less important

What? What's unconventional? No idea what you mean.

>         than the slope of the trendlines, can these plots be regenerated using more standard
>         log-scaled semiology? I.e., grid lines at the powers of 10 with minor ticks along the axes
>         showing log-spacing.

No idea about this. It looks like a standard log-log plot to me.

**Comment by wd15** [comment]
@tkphd: all the titles and legend names should be better now.

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1505.surge.sh

**Comment by tkphd** [comment]
Looks much better, thanks.
A minor quibble: in the first plot, $\mathcal{O}(k)$ is dashed and $\mathcal{O}(k^2)$ is dotted; in the second, $\mathcal{O}(h)$ is dotted and $\mathcal{O}(h^2)$ is dashed. Switching the order of one or the other for consistency would be preferable.

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1505.surge.sh

**Comment by wd15** [comment]
@tkphd, should be better now. Please take a look again.

**Review by tkphd — APPROVED** [review]
LGTM!

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1505.surge.sh

**Pull request merged**
