### PR TITLE
Implement specs for revision 0 of problems 5 and 6

### PR DESCRIPTION
**Pull request by wd15**
Address #424 

Implement spec for the hackathon versions of problems 5 and 6 from https://www.overleaf.com/read/nqjkdwyybvdz

When reviewing please check

  - http://random-cat-708.surge.sh/benchmarks/benchmark5-hackathon.ipynb
 
  - http://random-cat-708.surge.sh/benchmarks/benchmark6-hackathon.ipynb

The submission guidelines are not very complete for these two yet. I am planning on improving the submission guidelines for all the benchmarks as I work through getting the comparison displays better and uploading my own data.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-708.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/708)

### CODE REVIEW

**Comment by tkphd** [comment]
I'm adding the committee of authors as reviewers for this PR:
@amjokisaari, @drjamesawarren, @guyer, @heinono1, ... anyone else?

**Comment by tkphd** [comment]
Please add equation numbers, after #680.

**Comment by tkphd** [comment]
Please choose a standard citation method and apply it uniformly. For example,

([Jokisaari 2017](https://doi.org/10.1016/j.commatsci.2016.09.022)) and ([Guyer 2004a](https://doi.org/10.1103/PhysRevE.69.021603))

**Comment by tkphd** [comment]
In the scalar Stokes momentum equation, please write |**g**|.

**Comment by tkphd** [comment]
In the first paragraph of [Domain](http://random-cat-708.surge.sh/benchmarks/benchmark5-hackathon.ipynb/#Domain), `obstruction (case (b).` is missing a `)`.

**Comment by tkphd** [comment]
Figure 1 has blue shadow-artifacts around the three dots. Is there a hi-res source image we can convert to B&W?

**Comment by tkphd** [comment]
The final sentence isn't:

> All solid surfaces, including the boundary for the obstruction, have no-slip boundary conditions, that is, > ux=uy=0. The inlet velocity, on the left boundary, follows a parabolic profile described by
>
> ## Boundary Conditions
> ux(0,y)=−0.001(y−3)2+0.009.

**Comment by tkphd** [comment]
*x* and *y* in *x*-direction and *y*-direction should be italicized.

**Comment by tkphd** [comment]
In the [Submission Guidelines](http://random-cat-708.surge.sh/benchmarks/benchmark5-hackathon.ipynb/#Submission-Guidelines), we request `all three vector components of the velocity.` Since there's no curl in the equations, this must either mean `two vector components of velocity`, or `all three field components (velocity and density)`.

**Comment by tkphd** [comment]
## [Benchmark Problem 6](http://random-cat-708.surge.sh/benchmarks/benchmark6-hackathon.ipynb/)
Please choose a standard citation method and apply it uniformly. For example,
([Jokisaari 2017](https://doi.org/10.1016/j.commatsci.2016.09.022)) and ([Guyer 2004a](https://doi.org/10.1103/PhysRevE.69.021603)).

**Comment by tkphd** [comment]
At the end of [Governing Equations](http://random-cat-708.surge.sh/benchmarks/benchmark6-hackathon.ipynb/#Governing-Equations), provide the link to the [spinodal benchmark problem](https://pages.nist.gov/pfhub/benchmarks/benchmark1.ipynb).

**Comment by tkphd** [comment]
In [Domain](http://random-cat-708.surge.sh/benchmarks/benchmark6-hackathon.ipynb/#Domain), `shown in below` is not proper English. Can we number figures?

**Comment by tkphd** [comment]
- If we are going to refer to one geometry as `square`, we should name the other geometry and use it (I recommend `stele`), rather than `the other domain`.
- It would be better to use names that correspond to the figure labels, `(a)` and `(b)`, to remove ambiguity.
- Since proper figure-captioning is difficult in Markdown, consider splitting the geometric description into two sub-sections, with a final sub-section specifying the equations in terms of the sub-section identifiers. Or, for absolute clarity, accept some duplication and specify each sub-problem completely in isolation.

**Comment by tkphd** [comment]
In the last equation, use a third brace character (*e.g.* `{`, `}`) rather than nesting square bracketed terms. Also, use `\large{ ... \\ ... \large}` instead of `\left[ ... \right. \\ \left. ... \right]`.

**Comment by tkphd** [comment]
The [Submission Guidelines](http://random-cat-708.surge.sh/benchmarks/benchmark6-hackathon.ipynb/#Submission-Guidelines) instruct users to

> visualize the *c* and *Φ* fields during evolution
> plot horizontal line cuts through the center of the domain for *c*
> plot the total free energy of the system as a function of time

Assuming we wish to collect data, rather than just pictures, we need to request specific file formats and suggest desirable contents.

**Comment by wd15** [comment]
> Please add equation numbers, after #680.

Added equation numbers, but FYI required

```
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_HTML">
</script>
```

for rendering on the website. Note that, https://pages.nist.gov/pfhub/benchmarks/benchmark7.ipynb/ does not render equations (before this pull request is merged).

> In the scalar Stokes momentum equation, please write ρ|g| or ρg or ρg·j.

It's supposed to be *ρ***g**. It isn't a scalar equation.

> In the first paragraph of Domain, obstruction (case (b). is missing a ).

fixed

> Stokes Figure 1 has blue shadow-artifacts around the three dots. Is there a hi-res source image we can convert to B&W?

Converted to B&W and blue marks are gone now

> The final sentence isn't:

fixed now

> x and y in x-direction and y-direction should be italicized.

fixed now

> In the Submission Guidelines:

should be better now

> Please choose a standard citation method

done

> At the end of Governing Equations, provide the link to the spinodal benchmark problem.

done

> In Domain, shown in below is not proper English. Can we number figures? If not, consider rendering as a table, providing the caption as a row spanning both columns.

Can't seem to number figures, at least I can't get it working. I just used a subheading for each figure to give it a number and a title. Seems to look ok. Referring to domain (a) and domain (b) now.

> In the last equation, use a third brace character (e.g. {, }) rather than nesting square bracketed terms. Also, use \Bigg{ ... \\ ... \Bigg} instead of \left[ ... \right. \\ \left. ... \right].

\Bigg doesn't work for me in the notebook. I'm using braces now though

> The Submission Guidelines instruct users to

Submission guidelines for both problems are much better now.

**Comment by tkphd** [comment]
> >In the scalar Stokes momentum equation, please write *ρ*|**g**| or *ρ***g** or *ρ***g**·**j**.
>
> It's supposed to be *ρ***g**. It isn't a scalar equation.

This is untrue. The RHS is a scalar (zero), and every term but the last on the LHS evaluates to a scalar. The expression *ρ***g** breaks the equality and makes the equation ambiguous.

Please choose an alternative from the list of suggestions.

**Comment by tkphd** [comment]
Reviewed 6 of 12 files at r1, 7 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/708)*

**Comment by tkphd** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[benchmarks/benchmark5-hackathon.ipynb, line 229 at r3](https://reviewable.io:443/reviews/usnistgov/pfhub/708#-L4l4f9jTQW0pkdURf8x:-L4l4f9jTQW0pkdURf8y:b-9mklcs) ([raw file](https://github.com/usnistgov/pfhub/blob/418b40b6b67927cf485b088b88b07003b9883623/benchmarks/benchmark5-hackathon.ipynb#L229)):*
> - Link to your first CSV or JSON file, labeled `x_cut_plane` in the upload form; the columns or keys should be named `y`, `velocity_x`, `velocity_y` and `pressure`

---

*[benchmarks/benchmark5-hackathon.ipynb, line 231 at r3](https://reviewable.io:443/reviews/usnistgov/pfhub/708#-L4l5NXWMYaIzyew5wqX:-L4l5NXWMYaIzyew5wqY:bnxib0w) ([raw file](https://github.com/usnistgov/pfhub/blob/418b40b6b67927cf485b088b88b07003b9883623/benchmarks/benchmark5-hackathon.ipynb#L231)):*
> - Link to your second CSV or JSON file, labeled `y_cut_plane` in the upload form; the columns or keys should be named `x`, `velocity_x`, `velocity_y` and `pressure`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/708)*

**Comment by tkphd** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[benchmarks/benchmark6-hackathon.ipynb, line 188 at r3](https://reviewable.io:443/reviews/usnistgov/pfhub/708#-L4l6HwMhIBG2ISGI0JS:-L4l6HwMhIBG2ISGI0JT:b2xaael) ([raw file](https://github.com/usnistgov/pfhub/blob/418b40b6b67927cf485b088b88b07003b9883623/benchmarks/benchmark6-hackathon.ipynb#L188)):*
> ([Guyer 2004a][guyer2004phase], [Guyer 2004b][guyer2004phaseII])

---

*[benchmarks/benchmark6-hackathon.ipynb, line 240 at r3](https://reviewable.io:443/reviews/usnistgov/pfhub/708#-L4l6lFBsia2Y_vyHSn8:-L4l6lFBsia2Y_vyHSn9:b-fwjf6t) ([raw file](https://github.com/usnistgov/pfhub/blob/418b40b6b67927cf485b088b88b07003b9883623/benchmarks/benchmark6-hackathon.ipynb#L240)):*
>  - the free energy integrated across the entire domain, Eqn. 1, collected as frequently as is feasible

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/708)*

**Comment by wd15** [comment]
Review status: 9 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[benchmarks/benchmark5-hackathon.ipynb, line 229 at r3](https://beta.reviewable.io/reviews/usnistgov/pfhub/708#-L4l4f9jTQW0pkdURf8x:-L4lBVoxC2QX1HJQ8ulb:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/418b40b6b67927cf485b088b88b07003b9883623/benchmarks/benchmark5-hackathon.ipynb#L229)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> - Link to your first CSV or JSON file, labeled `x_cut_plane` in the upload form; the columns or keys should be named `y`, `velocity_x`, `velocity_y` and `pressure`
</blockquote></details>

Done.

---

*[benchmarks/benchmark5-hackathon.ipynb, line 231 at r3](https://beta.reviewable.io/reviews/usnistgov/pfhub/708#-L4l5NXWMYaIzyew5wqX:-L4lBWEd9dnbPb1gOR0z:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/418b40b6b67927cf485b088b88b07003b9883623/benchmarks/benchmark5-hackathon.ipynb#L231)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> - Link to your second CSV or JSON file, labeled `y_cut_plane` in the upload form; the columns or keys should be named `x`, `velocity_x`, `velocity_y` and `pressure`
</blockquote></details>

Done.

---

*[benchmarks/benchmark6-hackathon.ipynb, line 188 at r3](https://beta.reviewable.io/reviews/usnistgov/pfhub/708#-L4l6HwMhIBG2ISGI0JS:-L4lBovCEJ-St45-bOU5:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/418b40b6b67927cf485b088b88b07003b9883623/benchmarks/benchmark6-hackathon.ipynb#L188)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

> ([Guyer 2004a][guyer2004phase], [Guyer 2004b][guyer2004phaseII])
</blockquote></details>

Done.

---

*[benchmarks/benchmark6-hackathon.ipynb, line 240 at r3](https://beta.reviewable.io/reviews/usnistgov/pfhub/708#-L4l6lFBsia2Y_vyHSn8:-L4lBpG5B11mm1z4yKwd:b-896fix) ([raw file](https://github.com/usnistgov/pfhub/blob/418b40b6b67927cf485b088b88b07003b9883623/benchmarks/benchmark6-hackathon.ipynb#L240)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

>  - the free energy integrated across the entire domain, Eqn. 1, collected as frequently as is feasible
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/usnistgov/pfhub/708)*

**Comment by tkphd** [comment]
Reviewed 2 of 4 files at r4.
Review status: 11 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/708)*

**Comment by tkphd** [comment]
Reviewed 2 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/pfhub/708)*

**Pull request merged**
