### PR TITLE
Automate pull request comment for uploads

### PR DESCRIPTION
**Pull request by wd15**
Address #826

Automate pull request comment for uploads that includes the links to
the upload displays on Surge.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-838.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/838)

### CODE REVIEW

**Comment by tkphd** [comment]
Does this PR check any of the boxes in #826?

**Comment by wd15** [comment]
@tkphd, yes it addresses them all.

**Comment by wd15** [comment]
@tkphd, one other thing. This only works with pull requests from branches already on usnistgov/pfhub which is good for staticman. The problem is that secure environment variables are not available for pull requests from branches not on usnistgov/pfhub in Travis CI. Making it works requires using a third service of some sort.

**Comment by wd15** [comment]
I've cleaned this up a bit now. You can see how this should look in https://github.com/usnistgov/pfhub/pull/840 (the secend comment, the first is broken).

**Pull request merged**
