### PR TITLE
PFHub Upload: hiperc_cuda

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload

To review:

- Wait for the tests to pass.

- Go to http://random-cat-759.surge.sh/simulations/display/?sim=hiperc_cuda

| Field     | Content                                                                         |
| --------- | ------------------------------------------------------------------------------- |
| metadata  | [object Object]                                                                 |
| benchmark | [object Object]                                                                 |
| data      | [object Object],[object Object],[object Object],[object Object],[object Object] |
| date      | 1519052898                                                                      |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/759)

### CODE REVIEW

**Comment by wd15** [comment]
@tkphd, this doesn't have the temporal convergence data. Is that how you want it or did you forget to add it. Also, in BM7 we need to say what to name the data. Currently, I'm using "spatial" and "temporal". 

@stvdwtt, @tkphd, I think BM7 needs a separate "submission guidelines" section that has a succinct description of what needs to be uploaded and what to call the data.

**Comment by wd15** [comment]
@tkphd, ok, I'm going to fix and merge this and then you can branch if you want to add the temporal data.

**Comment by tkphd** [comment]
I haven't finished the temporal data yet -- looks like a flat line -- so this'll be a good live test of editing an existing upload. Methinks the name you give data matters less than the caption explaining what the dataset contains *e.g.* "Spatial convergence data for forward-time, O(k), centered-space, O(h^2), ..."

@wd15, what exactly needs to be "fixed"?

**Comment by tkphd** [comment]
Also, @wd15, any thoughts on #761? It'd be nice if HTML in captions was a thing.

**Comment by wd15** [comment]
On Mon, Feb 19, 2018 at 2:30 PM, Trevor Keller <notifications@github.com> wrote:
>
> I haven't finished the temporal data yet -- looks like a flat line -- so this'll be a good live test of editing an existing upload. Methinks the name you give data matters less than the caption explaining what the dataset contains e.g. "Spatial convergence data for forward-time, O(k), centered-space, O(h^2), ..."

Ok, well you can add that data to the YAML file when it's ready. I'll
move ahead with merging this anyway since I'm in the midst of doing
so.

> @wd15, what exactly needs to be "fixed"?

 - data renamed from spatial_convergece to spatial
 - version 1 to version 0
 - HiPerC to hiperc (stupid, I know, but I haven't downcased all the names yet)
 - run "make simulations"
 - have code deal with missing data ("temporal" is missing here) so
needs to be fixed for that

I'll make those changes to check things work properly

-- 
Daniel Wheeler

**Comment by wd15** [comment]
On Mon, Feb 19, 2018 at 2:32 PM, Trevor Keller <notifications@github.com> wrote:
>
> Also, @wd15, any thoughts on #761? It'd be nice if HTML in captions was a thing.

Yes, will do soon (either HTML or maybe markdown would be more
sensible). I'll make sure all fields with text render markdown. I
think that's the case for some others.

-- 
Daniel Wheeler

**Comment by wd15** [comment]
On Mon, Feb 19, 2018 at 2:30 PM, Trevor Keller <notifications@github.com> wrote:
>
> Methinks the name you give data matters less than the caption explaining what the dataset contains e.g. "Spatial convergence data for forward-time, O(k), centered-space, O(h^2), ..."

A computer program can't infer how to plot a dataset based on a description.

-- 
Daniel Wheeler

**Comment by wd15** [comment]
@tkphd, please check that the rendering of the comparison page is to your liking for your data

http://random-cat-759.surge.sh/simulations/7a.0/

**Comment by tkphd** [comment]
Looks about right, interesting that the error is higher. Something to look into!

**Pull request merged**
