### PR TITLE
PFHub Upload: fipy_1a_travis

### PR DESCRIPTION
**Pull request by wd15**
**A one line, short summary of intent.**

Links to issues such as "Fixes #XXX" or "Addresses #XXX".

A longer description and justification for the changes.

Raise any areas of concern.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-{pull-request-number}.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/837)

### CODE REVIEW

**Comment by wd15** [comment]
@ testing comments...

**Comment by wd15** [comment]
@tkphd testing comments...

**Comment by wd15** [comment]
@tkphd, thanks for the upload!

You can view your upload display at

 - random-cat-837.surge.sh/simulations/display/?sim=fipy_1a_travis

and

 - random-cat-837.surge.sh/simulations/null.null

Please review and confirm your approval to @wd15 by commenting in this pull request.

**Comment by tkphd** [comment]
I've been getting all kinds of e-mails, yeah!

**Comment by wd15** [comment]
@tkphd, sorry, you're my guinea pig. It'll stop at some point.

**Comment by tkphd** [comment]
No worries, mate.

**Comment by wd15** [comment]
@tkphd, thanks for the upload!

You can view your upload display at

 - https://random-cat-837.surge.sh/simulations/display/?sim=fipy_1a_travis

and

 - https://random-cat-837.surge.sh/simulations/null.null

Please review and confirm your approval to @wd15 by commenting in this pull request.

You can make further changes to this pull request by [editing the meta.yaml](https://github.com/usnistgov/pfhub/edit/staticman_blah/_data/simulations/fipy_1a_travis/meta.yaml?pr=%2Fusnistgov%2Fpfhub%2Fpull%2F837) associated with this pull request.

**Comment by wd15** [comment]
@tkphd, thanks for your PFHub upload! Your upload appears to have passed the tests.

You can view your upload display at

 - https://random-cat-837.surge.sh/simulations/display/?sim=fipy_1a_travis

and

 - https://random-cat-837.surge.sh/simulations/1a.1

Please review and confirm your approval to @wd15 by commenting in this pull request.

You can make further changes to this pull request by [editing the meta.yaml](https://github.com/usnistgov/pfhub/edit/staticman_blah/_data/simulations/fipy_1a_travis/meta.yaml?pr=%2Fusnistgov%2Fpfhub%2Fpull%2F837) associated with this pull request.

**Pull request closed without merging**
