### PR TITLE
upload: PRISMS_PF_sp

### PR DESCRIPTION
**Pull request by wd15**
This a new PFHub upload.

Wait for the tests to pass and a comment with a link to view the upload display will appear below.

upload: PRISMS_PF_sp
benchmark_id: 3a.1
github_id: stvdwtt

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/1134)

### CODE REVIEW

**Comment by pfhub** [comment]
@stvdwtt, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1134.surge.sh/simulations/display/?sim=PRISMS_PF_sp_update

and

 - https://random-cat-1134.surge.sh/simulations/3a.1

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1134.surge.sh/simulations/upload_form/?sim=PRISMS_PF_sp_update).

**Comment by stvdwtt** [comment]
Everything looks fine except that the contour doesn't show up on the main results page. It appears correctly on the individual upload page, though.

**Comment by wd15** [comment]
Thanks @stvdwtt, I'll try and figure out what's going on.

**Comment by pfhub** [comment]
@stvdwtt, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1134.surge.sh/simulations/display/?sim=PRISMS_PF_sp

and

 - https://random-cat-1134.surge.sh/simulations/3a.1

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1134.surge.sh/simulations/upload_form/?sim=PRISMS_PF_sp).

**Comment by pfhub** [comment]
@stvdwtt, thanks for your PFHub upload!

You can view your upload display at

 - https://random-cat-1134.surge.sh/simulations/display/?sim=PRISMS_PF_sp

and

 - https://random-cat-1134.surge.sh/simulations/3a.1

Please check that the tests pass below and then review and confirm your approval to @pfhub by commenting in this pull request.

If you think there is a mistake in your upload data, then you can resubmit the upload [at this link](https://random-cat-1134.surge.sh/simulations/upload_form/?sim=PRISMS_PF_sp).

**Pull request merged**
