### PR TITLE
PFHub Upload: PRISMSPF_Quad

### PR DESCRIPTION
**Pull request by staticmanapp**
This a new PFHub upload

To review:

- Wait for the tests to pass.

- Go to http://random-cat-722.surge.sh/simulations/display/?sim=PRISMSPF_Quad

| Field     | Content                                                         |
| --------- | --------------------------------------------------------------- |
| metadata  | [object Object]                                                 |
| benchmark | [object Object]                                                 |
| data      | [object Object],[object Object],[object Object],[object Object] |
| date      | 1518017863                                                      |
| layout    | post                                                            |
| message   |                                                                 |

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/722)

### CODE REVIEW

**Comment by tkphd** [comment]
@wd15, Travis-CI threw:
> pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
> - Enum '7a' does not exist. Path: '/benchmark/id'.
> - Key 'layout' was not defined. Path: ''.
> - Key 'message' was not defined. Path: ''.: Path: '/'>

**Comment by wd15** [comment]
@stvdwtt, do you have any numbers for run time and memory usage?

**Comment by stvdwtt** [comment]
I was intentionally keeping those blank, since they vary from run to run. I think that should be the standard practice for multi-simulation datasets.

**Comment by wd15** [comment]
@stvdwtt, I need to make the form problem dependent at some point. Benchmark 7 won't have any efficiency data associated with it. I think that makes sense. The only reservation I have is memory because accuracy is always a trade off with memory. We can discuss more at the meeting.

**Comment by wd15** [comment]
@stvdwtt, please give your approval to the images

http://random-cat-722.surge.sh/simulations/display/?sim=PRISMSPF_Quad

Are they okay?

**Comment by wd15** [comment]
On Thu, Feb 8, 2018 at 11:51 AM, Stephen DeWitt
<notifications@github.com> wrote:
>
> Typically, these plots are shown on a log-log scale (sorry I didn't mention that)

The individual simulation result pages are only really checks for your
data. The combined result pages for BM7 will have log-log plots when I
implement it for specific data sets. Basically, I'm not intending on
implementing fancy plots for the individual pages, just the basics.
The fancy plots are for the comparison pages. The form and schema
would get very complicated as the individual pages can host any data.
If this is something that needs to be addressed, then we need to file
it in a separate issue.

> The axis labels are just "the y-axis" and "the x-axis". For both plots the y-axis label should be "L2 Error". For the spatial convergence test the x-axis label should be "Mesh Size" and for the temporal convergence test it should be "Time Step".

Again, I'm not intending to fix that right now. I would need a more
complex form. We need a separate issue for this if we intend to change
the form and schema. To name x-axis and y-axis. We could default to
the names give on the form acutally, I'll file a ticket for that,
#732.

> The plot placement is not what I'd expect. One is above the bar above "Results" and one is below it. Either above or below is ok, as long as that's where both are. (I don't think any of the existing submission summary pages have multiple plots. It looks like they all have a single plot above the "Results" bar.)

It automatically showcases one result. I think it picks an image if
one is submitted, otherwise it picks a plot. Again this is a design
issue that we need to address separately. I'm not sure how to change
it, but again if we want something different then we need to file a
ticket.

> The bottom of the plots are cut off until I click on them. That seems like a universal problem that's outside the scope of this PR. I'll create a separate issue.

Ok, I moved that to milestone 0.5.

-- 
Daniel Wheeler

**Comment by stvdwtt** [comment]
Log-log plots: Ok, that makes sense. I thought the plots shown on the individual results page and the comparison page were most closely tied. The completely different look-and-feel should have made me realize that isn't the case.

Axis names: Ok, sounds good. Mostly I was thrown because I checked one of the [other simulation result pages](https://pages.nist.gov/pfhub/simulations/display/?sim=moose_2b_ia) and the axes had real labels, so I thought it was a unique issue with BM7.

Plot placement: I can open a ticket, although I'd view it as a very low priority.

Truncated plots: Sounds good.

**Comment by wd15** [comment]
On Thu, Feb 8, 2018 at 12:51 PM, Stephen DeWitt
<notifications@github.com> wrote:
>
> Axis names: Ok, sounds good. Mostly I was thrown because I checked one of the other simulation result pages and the axes had real labels, so I thought it was a unique issue with BM7.

Yeah, you're right, I'll investigate that as part of #732

--
Daniel Wheeler

**Pull request merged**
