### PR TITLE
post and link user stories

### LINKED ISSUE #993: post and link user stories
- [x] Transcribe from [OverLeaf](https://www.overleaf.com/project/59d6474d5add804f71cb6ff6)
- [x] Link Welcome paragraph keywords to user stories

Related to #427, #430, #482, #499, #533.

### PR DESCRIPTION
**Pull request by tkphd**
Closes #993.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging
or closing this pull request.**

[live-site]: http://random-cat-994.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/pfhub/994)

### CODE REVIEW

**Comment by tkphd** [comment]
@wd15, would you mind looking at the [result]() and weighing in on the HTML code?
On GitHub, the headers appear with little permalink icons when moused over, and I think it would be cool to  have that. At the moment, I have an awkward cross between an anchor link and a blue headline. 

Maybe the near-term answer is to revert 2191757, but your expert opinion would be welcome.

**Comment by wd15** [comment]
@tkphd, I'm not sure I'm fully onboard with this. What you've done is really nice and lays out exactly where we need to go. However, I'm not sure about the utility of laying out a list of hopeful items that may never be implemented. From my perspective, I would prefer to use the phrase "To help this new user come up to speed, the website provides the following" and then just list what the website actually does right now and also include links. For example, let's link to background material defining what phase field actually is in the first bullet point if we have that on the website somewhere. Maybe we can have one or two extra items with "coming soon" attached and then create an issue for those and link to the issue. That's my preference. For example, we actually have a list of suggested codes, so let's link to that.

I'll look into the HTML issue with mouse over permalinks.

**Comment by wd15** [comment]
@tkphd, I've added permalink icons in #997. You will need to reverse some of your changes here. There is no need to add the `<a>` elements anymore.

**Comment by tkphd** [comment]
@wd15, thanks again for the feedback, and apologies for the latency. I believe the revised build is failing do to undefined anchors, which ought to be resolved when merged. If you can have another look, I'd appreciate it.

**Comment by wd15** [comment]
Also, I think this can be rebased into fewer commits so feel free to to that as well.

**Comment by tkphd** [comment]
Removing slashes did nothing; reverted and rebased to 2 commits. Over to you.

**Comment by wd15** [comment]
What's going on here is that the header link is built by javascript, but htmlproofer is only proofing the static version of the website that hasn't been generated through a browser.

**Pull request merged**
