### PR TITLE
notebooks: fix eclipse to be ellipse in bm4

### PR DESCRIPTION
**Pull request by wd15**
Address #1501

### CODE REVIEW

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1503.surge.sh

**Comment by pfhub** [comment]
@wd15, the new version of the PFHub website is available at https://random-cat-1503.surge.sh

**Comment by wd15** [comment]
@tkphd, this one is ready for you to review

**Review by tkphd — APPROVED** [review]
LGTM!

**Comment by pfhub** [comment]
Successful teardown of random-cat-1503.surge.sh

**Pull request merged**
